/* machine-generated file, do not edit */
const char *kf_frag_glsl =
"\n"
"vec3 colour(void);\n"
"\n"
"\n"
"\n"
"\n"
"uniform ivec2 ImageSize;\n"
"\n"
"uniform sampler1D KFP_Palette;\n"
"\n"
"uniform vec3 KFP_InteriorColor;\n"
"\n"
"uniform bool KFP_ShowGlitches;\n"
"\n"
"uniform uvec2 KFP_Iterations;\n"
"uniform uvec2 KFP_IterationsMin;\n"
"uniform uvec2 KFP_IterationsMax;\n"
"\n"
"uniform uint KFP_JitterSeed;\n"
"uniform int KFP_JitterShape;\n"
"uniform float KFP_JitterScale;\n"
"\n"
"uniform float KFP_IterDiv;\n"
"uniform float KFP_ColorOffset;\n"
"\n"
"uniform int KFP_ColorMethod;\n"
"#define ColorMethod_Standard 0\n"
"#define ColorMethod_SquareRoot 1\n"
"#define ColorMethod_CubicRoot 2\n"
"#define ColorMethod_Logarithm 3\n"
"#define ColorMethod_Stretched 4\n"
"#define ColorMethod_DistanceLinear 5\n"
"#define ColorMethod_DEPlusStandard 6\n"
"#define ColorMethod_DistanceLog 7\n"
"#define ColorMethod_DistanceSqrt 8\n"
"#define ColorMethod_LogLog 9\n"
"#define ColorMethod_ATan 10\n"
"#define ColorMethod_FourthRoot 11\n"
"\n"
"uniform int KFP_Differences;\n"
"#define Differences_Traditional 0\n"
"#define Differences_Forward3x3 1\n"
"#define Differences_Central3x3 2\n"
"#define Differences_Diagonal2x2 3\n"
"#define Differences_LeastSquares2x2 4\n"
"#define Differences_LeastSquares3x3 5\n"
"#define Differences_Laplacian3x3 6\n"
"#define Differences_Analytic 7\n"
"\n"
"uniform float KFP_PhaseColorStrength;\n"
"\n"
"uniform bool KFP_Smooth;\n"
"uniform bool KFP_Flat;\n"
"uniform bool KFP_InverseTransition;\n"
"\n"
"uniform bool KFP_MultiWavesEnabled;\n"
"uniform bool KFP_MultiWavesBlend;\n"
"uniform int KFP_MultiWavesCount;\n"
"#define KFP_MultiWavesCountMax 32\n"
"uniform ivec3 KFP_MultiWaves[KFP_MultiWavesCountMax];\n"
"\n"
"uniform bool KFP_Slopes;\n"
"uniform float KFP_SlopePower;\n"
"uniform float KFP_SlopeRatio;\n"
"uniform vec2 KFP_SlopeDir;\n"
"\n"
"uniform sampler2D KFP_Texture;\n"
"uniform bool KFP_TextureEnabled;\n"
"uniform float KFP_TextureMerge;\n"
"uniform float KFP_TexturePower;\n"
"uniform float KFP_TextureRatio;\n"
"\n"
"uniform bool KFP_sRGB;\n"
"\n"
"\n"
"\n"
"\n"
"#if __VERSION__ >= 330\n"
"layout(location = 0, index = 0) out vec4 Internal_Colour;\n"
"#else\n"
"#define Internal_Colour gl_FragColor\n"
"#endif\n"
"\n"
"uniform usampler2D Internal_N1;\n"
"uniform usampler2D Internal_N0;\n"
"uniform sampler2D Internal_NF;\n"
"uniform sampler2D Internal_T;\n"
"uniform sampler2D Internal_DEX;\n"
"uniform sampler2D Internal_DEY;\n"
"\n"
"uniform ivec2 Internal_TilePadding;\n"
"uniform ivec2 Internal_TileOrigin;\n"
"uniform ivec2 Internal_TileSize;\n"
"\n"
"uniform float Internal_ZoomLog2;\n"
"\n"
"\n"
"uniform float Internal_Zero;\n"
"float Internal_One = 1.0;\n"
"float EXACT(float a) { return Internal_One * a; }\n"
"\n"
"#if __VERSION__ >= 400\n"
"float _builtin_ldexp(float a, int b) { return ldexp(a, b); }\n"
"float ldexp(float a, int b) { return _builtin_ldexp(a, b); }\n"
"#else\n"
"float ldexp(float a, int b) { return a * exp2(b); }\n"
"#endif\n"
"\n"
"\n"
"\n"
"\n"
"int _builtin_abs(int a) { return abs(a); }\n"
"ivec2 _builtin_abs(ivec2 a) { return abs(a); }\n"
"ivec3 _builtin_abs(ivec3 a) { return abs(a); }\n"
"ivec4 _builtin_abs(ivec4 a) { return abs(a); }\n"
"float _builtin_abs(float a) { return abs(a); }\n"
"vec2 _builtin_abs(vec2 a) { return abs(a); }\n"
"vec3 _builtin_abs(vec3 a) { return abs(a); }\n"
"vec4 _builtin_abs(vec4 a) { return abs(a); }\n"
"#if __VERSION__ >= 400\n"
"double _builtin_abs(double a) { return abs(a); }\n"
"dvec2 _builtin_abs(dvec2 a) { return abs(a); }\n"
"dvec3 _builtin_abs(dvec3 a) { return abs(a); }\n"
"dvec4 _builtin_abs(dvec4 a) { return abs(a); }\n"
"#endif\n"
"\n"
"int abs(int a) { return _builtin_abs(a); }\n"
"ivec2 abs(ivec2 a) { return _builtin_abs(a); }\n"
"ivec3 abs(ivec3 a) { return _builtin_abs(a); }\n"
"ivec4 abs(ivec4 a) { return _builtin_abs(a); }\n"
"float abs(float a) { return _builtin_abs(a); }\n"
"vec2 abs(vec2 a) { return _builtin_abs(a); }\n"
"vec3 abs(vec3 a) { return _builtin_abs(a); }\n"
"vec4 abs(vec4 a) { return _builtin_abs(a); }\n"
"#if __VERSION__ >= 400\n"
"double abs(double a) { return _builtin_abs(a); }\n"
"dvec2 abs(dvec2 a) { return _builtin_abs(a); }\n"
"dvec3 abs(dvec3 a) { return _builtin_abs(a); }\n"
"dvec4 abs(dvec4 a) { return _builtin_abs(a); }\n"
"#endif\n"
"\n"
"\n"
"\n"
"\n"
"float _builtin_sqrt(float a) { return sqrt(a); }\n"
"vec2 _builtin_sqrt(vec2 a) { return sqrt(a); }\n"
"vec3 _builtin_sqrt(vec3 a) { return sqrt(a); }\n"
"vec4 _builtin_sqrt(vec4 a) { return sqrt(a); }\n"
"#if __VERSION__ >= 400\n"
"double _builtin_sqrt(double a) { return sqrt(a); }\n"
"dvec2 _builtin_sqrt(dvec2 a) { return sqrt(a); }\n"
"dvec3 _builtin_sqrt(dvec3 a) { return sqrt(a); }\n"
"dvec4 _builtin_sqrt(dvec4 a) { return sqrt(a); }\n"
"#endif\n"
"\n"
"float sqrt(float a) { return _builtin_sqrt(a); }\n"
"vec2 sqrt(vec2 a) { return _builtin_sqrt(a); }\n"
"vec3 sqrt(vec3 a) { return _builtin_sqrt(a); }\n"
"vec4 sqrt(vec4 a) { return _builtin_sqrt(a); }\n"
"#if __VERSION__ >= 400\n"
"double sqrt(double a) { return _builtin_sqrt(a); }\n"
"dvec2 sqrt(dvec2 a) { return _builtin_sqrt(a); }\n"
"dvec3 sqrt(dvec3 a) { return _builtin_sqrt(a); }\n"
"dvec4 sqrt(dvec4 a) { return _builtin_sqrt(a); }\n"
"#endif\n"
"\n"
"\n"
"\n"
"\n"
"float _builtin_floor(float a) { return floor(a); }\n"
"vec2 _builtin_floor(vec2 a) { return floor(a); }\n"
"vec3 _builtin_floor(vec3 a) { return floor(a); }\n"
"vec4 _builtin_floor(vec4 a) { return floor(a); }\n"
"#if __VERSION__ >= 400\n"
"double _builtin_floor(double a) { return floor(a); }\n"
"dvec2 _builtin_floor(dvec2 a) { return floor(a); }\n"
"dvec3 _builtin_floor(dvec3 a) { return floor(a); }\n"
"dvec4 _builtin_floor(dvec4 a) { return floor(a); }\n"
"#endif\n"
"\n"
"float floor(float a) { return _builtin_floor(a); }\n"
"vec2 floor(vec2 a) { return _builtin_floor(a); }\n"
"vec3 floor(vec3 a) { return _builtin_floor(a); }\n"
"vec4 floor(vec4 a) { return _builtin_floor(a); }\n"
"#if __VERSION__ >= 400\n"
"double floor(double a) { return _builtin_floor(a); }\n"
"dvec2 floor(dvec2 a) { return _builtin_floor(a); }\n"
"dvec3 floor(dvec3 a) { return _builtin_floor(a); }\n"
"dvec4 floor(dvec4 a) { return _builtin_floor(a); }\n"
"#endif\n"
"\n"
"\n"
"\n"
"\n"
"float _builtin_ceil(float a) { return ceil(a); }\n"
"vec2 _builtin_ceil(vec2 a) { return ceil(a); }\n"
"vec3 _builtin_ceil(vec3 a) { return ceil(a); }\n"
"vec4 _builtin_ceil(vec4 a) { return ceil(a); }\n"
"#if __VERSION__ >= 400\n"
"double _builtin_ceil(double a) { return ceil(a); }\n"
"dvec2 _builtin_ceil(dvec2 a) { return ceil(a); }\n"
"dvec3 _builtin_ceil(dvec3 a) { return ceil(a); }\n"
"dvec4 _builtin_ceil(dvec4 a) { return ceil(a); }\n"
"#endif\n"
"\n"
"float ceil(float a) { return _builtin_ceil(a); }\n"
"vec2 ceil(vec2 a) { return _builtin_ceil(a); }\n"
"vec3 ceil(vec3 a) { return _builtin_ceil(a); }\n"
"vec4 ceil(vec4 a) { return _builtin_ceil(a); }\n"
"#if __VERSION__ >= 400\n"
"double ceil(double a) { return _builtin_ceil(a); }\n"
"dvec2 ceil(dvec2 a) { return _builtin_ceil(a); }\n"
"dvec3 ceil(dvec3 a) { return _builtin_ceil(a); }\n"
"dvec4 ceil(dvec4 a) { return _builtin_ceil(a); }\n"
"#endif\n"
"\n"
"\n"
"\n"
"\n"
"float _builtin_exp(float a) { return exp(a); }\n"
"vec2 _builtin_exp(vec2 a) { return exp(a); }\n"
"vec3 _builtin_exp(vec3 a) { return exp(a); }\n"
"vec4 _builtin_exp(vec4 a) { return exp(a); }\n"
"\n"
"float exp(float a) { return _builtin_exp(a); }\n"
"vec2 exp(vec2 a) { return _builtin_exp(a); }\n"
"vec3 exp(vec3 a) { return _builtin_exp(a); }\n"
"vec4 exp(vec4 a) { return _builtin_exp(a); }\n"
"\n"
"\n"
"\n"
"\n"
"float _builtin_log(float a) { return log(a); }\n"
"vec2 _builtin_log(vec2 a) { return log(a); }\n"
"vec3 _builtin_log(vec3 a) { return log(a); }\n"
"vec4 _builtin_log(vec4 a) { return log(a); }\n"
"\n"
"float log(float a) { return _builtin_log(a); }\n"
"vec2 log(vec2 a) { return _builtin_log(a); }\n"
"vec3 log(vec3 a) { return _builtin_log(a); }\n"
"vec4 log(vec4 a) { return _builtin_log(a); }\n"
"\n"
"\n"
"\n"
"\n"
"float _builtin_sin(float a) { return sin(a); }\n"
"vec2 _builtin_sin(vec2 a) { return sin(a); }\n"
"vec3 _builtin_sin(vec3 a) { return sin(a); }\n"
"vec4 _builtin_sin(vec4 a) { return sin(a); }\n"
"\n"
"float sin(float a) { return _builtin_sin(a); }\n"
"vec2 sin(vec2 a) { return _builtin_sin(a); }\n"
"vec3 sin(vec3 a) { return _builtin_sin(a); }\n"
"vec4 sin(vec4 a) { return _builtin_sin(a); }\n"
"\n"
"\n"
"\n"
"\n"
"float _builtin_cos(float a) { return cos(a); }\n"
"vec2 _builtin_cos(vec2 a) { return cos(a); }\n"
"vec3 _builtin_cos(vec3 a) { return cos(a); }\n"
"vec4 _builtin_cos(vec4 a) { return cos(a); }\n"
"\n"
"float cos(float a) { return _builtin_cos(a); }\n"
"vec2 cos(vec2 a) { return _builtin_cos(a); }\n"
"vec3 cos(vec3 a) { return _builtin_cos(a); }\n"
"vec4 cos(vec4 a) { return _builtin_cos(a); }\n"
"\n"
"\n"
"\n"
"\n"
"float _builtin_tan(float a) { return tan(a); }\n"
"vec2 _builtin_tan(vec2 a) { return tan(a); }\n"
"vec3 _builtin_tan(vec3 a) { return tan(a); }\n"
"vec4 _builtin_tan(vec4 a) { return tan(a); }\n"
"\n"
"float tan(float a) { return _builtin_tan(a); }\n"
"vec2 tan(vec2 a) { return _builtin_tan(a); }\n"
"vec3 tan(vec3 a) { return _builtin_tan(a); }\n"
"vec4 tan(vec4 a) { return _builtin_tan(a); }\n"
"\n"
"\n"
"\n"
"\n"
"float _builtin_sinh(float a) { return sinh(a); }\n"
"vec2 _builtin_sinh(vec2 a) { return sinh(a); }\n"
"vec3 _builtin_sinh(vec3 a) { return sinh(a); }\n"
"vec4 _builtin_sinh(vec4 a) { return sinh(a); }\n"
"\n"
"float sinh(float a) { return _builtin_sinh(a); }\n"
"vec2 sinh(vec2 a) { return _builtin_sinh(a); }\n"
"vec3 sinh(vec3 a) { return _builtin_sinh(a); }\n"
"vec4 sinh(vec4 a) { return _builtin_sinh(a); }\n"
"\n"
"\n"
"\n"
"\n"
"float _builtin_cosh(float a) { return cosh(a); }\n"
"vec2 _builtin_cosh(vec2 a) { return cosh(a); }\n"
"vec3 _builtin_cosh(vec3 a) { return cosh(a); }\n"
"vec4 _builtin_cosh(vec4 a) { return cosh(a); }\n"
"\n"
"float cosh(float a) { return _builtin_cosh(a); }\n"
"vec2 cosh(vec2 a) { return _builtin_cosh(a); }\n"
"vec3 cosh(vec3 a) { return _builtin_cosh(a); }\n"
"vec4 cosh(vec4 a) { return _builtin_cosh(a); }\n"
"\n"
"\n"
"\n"
"\n"
"float _builtin_tanh(float a) { return tanh(a); }\n"
"vec2 _builtin_tanh(vec2 a) { return tanh(a); }\n"
"vec3 _builtin_tanh(vec3 a) { return tanh(a); }\n"
"vec4 _builtin_tanh(vec4 a) { return tanh(a); }\n"
"\n"
"float tanh(float a) { return _builtin_tanh(a); }\n"
"vec2 tanh(vec2 a) { return _builtin_tanh(a); }\n"
"vec3 tanh(vec3 a) { return _builtin_tanh(a); }\n"
"vec4 tanh(vec4 a) { return _builtin_tanh(a); }\n"
"\n"
"\n"
"\n"
"\n"
"float _builtin_asin(float a) { return asin(a); }\n"
"vec2 _builtin_asin(vec2 a) { return asin(a); }\n"
"vec3 _builtin_asin(vec3 a) { return asin(a); }\n"
"vec4 _builtin_asin(vec4 a) { return asin(a); }\n"
"\n"
"float asin(float a) { return _builtin_asin(a); }\n"
"vec2 asin(vec2 a) { return _builtin_asin(a); }\n"
"vec3 asin(vec3 a) { return _builtin_asin(a); }\n"
"vec4 asin(vec4 a) { return _builtin_asin(a); }\n"
"\n"
"\n"
"\n"
"\n"
"float _builtin_acos(float a) { return acos(a); }\n"
"vec2 _builtin_acos(vec2 a) { return acos(a); }\n"
"vec3 _builtin_acos(vec3 a) { return acos(a); }\n"
"vec4 _builtin_acos(vec4 a) { return acos(a); }\n"
"\n"
"float acos(float a) { return _builtin_acos(a); }\n"
"vec2 acos(vec2 a) { return _builtin_acos(a); }\n"
"vec3 acos(vec3 a) { return _builtin_acos(a); }\n"
"vec4 acos(vec4 a) { return _builtin_acos(a); }\n"
"\n"
"\n"
"\n"
"\n"
"float _builtin_atan(float a) { return atan(a); }\n"
"vec2 _builtin_atan(vec2 a) { return atan(a); }\n"
"vec3 _builtin_atan(vec3 a) { return atan(a); }\n"
"vec4 _builtin_atan(vec4 a) { return atan(a); }\n"
"\n"
"float _builtin_atan(float a, float b) { return atan(a, b); }\n"
"vec2 _builtin_atan(vec2 a, vec2 b) { return atan(a, b); }\n"
"vec3 _builtin_atan(vec3 a, vec3 b) { return atan(a, b); }\n"
"vec4 _builtin_atan(vec4 a, vec4 b) { return atan(a, b); }\n"
"\n"
"float atan(float a) { return _builtin_atan(a); }\n"
"vec2 atan(vec2 a) { return _builtin_atan(a); }\n"
"vec3 atan(vec3 a) { return _builtin_atan(a); }\n"
"vec4 atan(vec4 a) { return _builtin_atan(a); }\n"
"\n"
"float atan(float a, float b) { return _builtin_atan(a, b); }\n"
"vec2 atan(vec2 a, vec2 b) { return _builtin_atan(a, b); }\n"
"vec3 atan(vec3 a, vec3 b) { return _builtin_atan(a, b); }\n"
"vec4 atan(vec4 a, vec4 b) { return _builtin_atan(a, b); }\n"
"\n"
"\n"
"\n"
"\n"
"float _builtin_asinh(float a) { return asinh(a); }\n"
"vec2 _builtin_asinh(vec2 a) { return asinh(a); }\n"
"vec3 _builtin_asinh(vec3 a) { return asinh(a); }\n"
"vec4 _builtin_asinh(vec4 a) { return asinh(a); }\n"
"\n"
"float asinh(float a) { return _builtin_asinh(a); }\n"
"vec2 asinh(vec2 a) { return _builtin_asinh(a); }\n"
"vec3 asinh(vec3 a) { return _builtin_asinh(a); }\n"
"vec4 asinh(vec4 a) { return _builtin_asinh(a); }\n"
"\n"
"\n"
"\n"
"\n"
"float _builtin_acosh(float a) { return acosh(a); }\n"
"vec2 _builtin_acosh(vec2 a) { return acosh(a); }\n"
"vec3 _builtin_acosh(vec3 a) { return acosh(a); }\n"
"vec4 _builtin_acosh(vec4 a) { return acosh(a); }\n"
"\n"
"float acosh(float a) { return _builtin_acosh(a); }\n"
"vec2 acosh(vec2 a) { return _builtin_acosh(a); }\n"
"vec3 acosh(vec3 a) { return _builtin_acosh(a); }\n"
"vec4 acosh(vec4 a) { return _builtin_acosh(a); }\n"
"\n"
"\n"
"\n"
"\n"
"float _builtin_atanh(float a) { return atanh(a); }\n"
"vec2 _builtin_atanh(vec2 a) { return atanh(a); }\n"
"vec3 _builtin_atanh(vec3 a) { return atanh(a); }\n"
"vec4 _builtin_atanh(vec4 a) { return atanh(a); }\n"
"\n"
"float atanh(float a) { return _builtin_atanh(a); }\n"
"vec2 atanh(vec2 a) { return _builtin_atanh(a); }\n"
"vec3 atanh(vec3 a) { return _builtin_atanh(a); }\n"
"vec4 atanh(vec4 a) { return _builtin_atanh(a); }\n"
"\n"
"\n"
"\n"
"\n"
"float _builtin_pow(float a, float b) { return pow(a, b); }\n"
"vec2 _builtin_pow(vec2 a, vec2 b) { return pow(a, b); }\n"
"vec3 _builtin_pow(vec3 a, vec3 b) { return pow(a, b); }\n"
"vec4 _builtin_pow(vec4 a, vec4 b) { return pow(a, b); }\n"
"\n"
"float pow(float a, float b) { return _builtin_pow(a, b); }\n"
"vec2 pow(vec2 a, vec2 b) { return _builtin_pow(a, b); }\n"
"vec3 pow(vec3 a, vec3 b) { return _builtin_pow(a, b); }\n"
"vec4 pow(vec4 a, vec4 b) { return _builtin_pow(a, b); }\n"
"\n"
"\n"
"\n"
"\n"
"float _builtin_max(float a, float b) { return max(a, b); }\n"
"vec2 _builtin_max(vec2 a, vec2 b) { return max(a, b); }\n"
"vec3 _builtin_max(vec3 a, vec3 b) { return max(a, b); }\n"
"vec4 _builtin_max(vec4 a, vec4 b) { return max(a, b); }\n"
"vec2 _builtin_max(vec2 a, float b) { return max(a, b); }\n"
"vec3 _builtin_max(vec3 a, float b) { return max(a, b); }\n"
"vec4 _builtin_max(vec4 a, float b) { return max(a, b); }\n"
"int _builtin_max(int a, int b) { return max(a, b); }\n"
"ivec2 _builtin_max(ivec2 a, ivec2 b) { return max(a, b); }\n"
"ivec3 _builtin_max(ivec3 a, ivec3 b) { return max(a, b); }\n"
"ivec4 _builtin_max(ivec4 a, ivec4 b) { return max(a, b); }\n"
"ivec2 _builtin_max(ivec2 a, int b) { return max(a, b); }\n"
"ivec3 _builtin_max(ivec3 a, int b) { return max(a, b); }\n"
"ivec4 _builtin_max(ivec4 a, int b) { return max(a, b); }\n"
"uint _builtin_max(uint a, uint b) { return max(a, b); }\n"
"uvec2 _builtin_max(uvec2 a, uvec2 b) { return max(a, b); }\n"
"uvec3 _builtin_max(uvec3 a, uvec3 b) { return max(a, b); }\n"
"uvec4 _builtin_max(uvec4 a, uvec4 b) { return max(a, b); }\n"
"uvec2 _builtin_max(uvec2 a, uint b) { return max(a, b); }\n"
"uvec3 _builtin_max(uvec3 a, uint b) { return max(a, b); }\n"
"uvec4 _builtin_max(uvec4 a, uint b) { return max(a, b); }\n"
"#if __VERSION__ >= 400\n"
"double _builtin_max(double a, double b) { return max(a, b); }\n"
"dvec2 _builtin_max(dvec2 a, dvec2 b) { return max(a, b); }\n"
"dvec3 _builtin_max(dvec3 a, dvec3 b) { return max(a, b); }\n"
"dvec4 _builtin_max(dvec4 a, dvec4 b) { return max(a, b); }\n"
"dvec2 _builtin_max(dvec2 a, double b) { return max(a, b); }\n"
"dvec3 _builtin_max(dvec3 a, double b) { return max(a, b); }\n"
"dvec4 _builtin_max(dvec4 a, double b) { return max(a, b); }\n"
"#endif\n"
"\n"
"float max(float a, float b) { return _builtin_max(a, b); }\n"
"vec2 max(vec2 a, vec2 b) { return _builtin_max(a, b); }\n"
"vec3 max(vec3 a, vec3 b) { return _builtin_max(a, b); }\n"
"vec4 max(vec4 a, vec4 b) { return _builtin_max(a, b); }\n"
"vec2 max(vec2 a, float b) { return _builtin_max(a, b); }\n"
"vec3 max(vec3 a, float b) { return _builtin_max(a, b); }\n"
"vec4 max(vec4 a, float b) { return _builtin_max(a, b); }\n"
"int max(int a, int b) { return _builtin_max(a, b); }\n"
"ivec2 max(ivec2 a, ivec2 b) { return _builtin_max(a, b); }\n"
"ivec3 max(ivec3 a, ivec3 b) { return _builtin_max(a, b); }\n"
"ivec4 max(ivec4 a, ivec4 b) { return _builtin_max(a, b); }\n"
"ivec2 max(ivec2 a, int b) { return _builtin_max(a, b); }\n"
"ivec3 max(ivec3 a, int b) { return _builtin_max(a, b); }\n"
"ivec4 max(ivec4 a, int b) { return _builtin_max(a, b); }\n"
"uint max(uint a, uint b) { return _builtin_max(a, b); }\n"
"uvec2 max(uvec2 a, uvec2 b) { return _builtin_max(a, b); }\n"
"uvec3 max(uvec3 a, uvec3 b) { return _builtin_max(a, b); }\n"
"uvec4 max(uvec4 a, uvec4 b) { return _builtin_max(a, b); }\n"
"uvec2 max(uvec2 a, uint b) { return _builtin_max(a, b); }\n"
"uvec3 max(uvec3 a, uint b) { return _builtin_max(a, b); }\n"
"uvec4 max(uvec4 a, uint b) { return _builtin_max(a, b); }\n"
"#if __VERSION__ >= 400\n"
"double max(double a, double b) { return _builtin_max(a, b); }\n"
"dvec2 max(dvec2 a, dvec2 b) { return _builtin_max(a, b); }\n"
"dvec3 max(dvec3 a, dvec3 b) { return _builtin_max(a, b); }\n"
"dvec4 max(dvec4 a, dvec4 b) { return _builtin_max(a, b); }\n"
"dvec2 max(dvec2 a, double b) { return _builtin_max(a, b); }\n"
"dvec3 max(dvec3 a, double b) { return _builtin_max(a, b); }\n"
"dvec4 max(dvec4 a, double b) { return _builtin_max(a, b); }\n"
"#endif\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"#if __VERSION__ >= 400\n"
"#define QD_FMS(a,b,s) fma(a,b,-s)\n"
"#endif\n"
"\n"
"#define QD_IEEE_ADD\n"
"\n"
"struct float49 { float x[2]; };\n"
"float49 float49_() { return float49(float[2](0.0, 0.0)); }\n"
"float49 float49_(float hi) { return float49(float[2](hi, 0.0)); }\n"
"float49 float49_(float hi, float lo) { return float49(float[2](hi, lo)); }\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*\n"
"This work was supported by the Director, Office of Science, Division\n"
"of Mathematical, Information, and Computational Sciences of the\n"
"U.S. Department of Energy under contract numbers DE-AC03-76SF00098 and\n"
"DE-AC02-05CH11231.\n"
"\n"
"Copyright (c) 2003-2009, The Regents of the University of California,\n"
"through Lawrence Berkeley National Laboratory (subject to receipt of\n"
"any required approvals from U.S. Dept. of Energy) All rights reserved.\n"
"\n"
"By downloading or using this software you are agreeing to the modified\n"
"BSD license that is in file BSD-LBNL-License.doc in the main ARPREC\n"
"directory. If you wish to use the software for commercial purposes\n"
"please contact the Technology Transfer Department at TTD@lbl.gov or\n"
"call 510-286-6457.\n"
"*/\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*\n"
"1. Redistribution and use in source and binary forms, with or without\n"
"modification, are permitted provided that the following conditions are\n"
"met:\n"
"\n"
"(1) Redistributions of source code must retain the copyright notice,\n"
"this list of conditions and the following disclaimer.\n"
"\n"
"(2) Redistributions in binary form must reproduce the copyright notice,\n"
"this list of conditions and the following disclaimer in the\n"
"documentation and/or other materials provided with the distribution.\n"
"\n"
"(3) Neither the name of the University of California, Lawrence Berkeley\n"
"National Laboratory, U.S. Dept. of Energy nor the names of its\n"
"contributors may be used to endorse or promote products derived from\n"
"this software without specific prior written permission.\n"
"\n"
"2. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
"AS IS AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A\n"
"PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT\n"
"OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n"
"SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\n"
"LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n"
"DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\n"
"THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n"
"(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n"
"OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
"\n"
"3. You are under no obligation whatsoever to provide any bug fixes,\n"
"patches, or upgrades to the features, functionality or performance of\n"
"the source code (Enhancements) to anyone; however, if you choose to\n"
"make your Enhancements available either publicly, or directly to\n"
"Lawrence Berkeley National Laboratory, without imposing a separate\n"
"written license agreement for such Enhancements, then you hereby grant\n"
"the following license: a non-exclusive, royalty-free perpetual license\n"
"to install, use, modify, prepare derivative works, incorporate into\n"
"other computer software, distribute, and sublicense such enhancements\n"
"or derivative works thereof, in binary and source code form.\n"
"*/\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*\n"
" * include/inline.h\n"
" *\n"
" * This work was supported by the Director, Office of Science, Division\n"
" * of Mathematical, Information, and Computational Sciences of the\n"
" * U.S. Department of Energy under contract number DE-AC03-76SF00098.\n"
" *\n"
" * Copyright (c) 2000-2001\n"
" *\n"
" * This file contains the basic functions used both by double-double\n"
" * and quad-double package.  These are declared as inline functions as\n"
" * they are the smallest building blocks of the double-double and\n"
" * quad-double arithmetic.\n"
" */\n"
"\n"
"#define _QD_SPLITTER     4097.0       \n"
"#define _QD_SPLIT_THRESH 4.1538375e34 \n"
"\n"
"const float _d_nan = 0.0 / 0.0;\n"
"const float _d_inf = 1.0 / 0.0;\n"
"\n"
"/*\n"
"ff :: Double -> (Float, Float)\n"
"ff d =\n"
"  let hi :: Float\n"
"      hi = realToFrac d\n"
"  in (hi, realToFrac (d - realToFrac hi))\n"
"*/\n"
"const float49 f49_nan = float49(float[2](_d_nan, _d_nan));\n"
"const float49 f49_inf = float49(float[2](_d_inf, _d_inf));\n"
"const float49 f49_0 = float49(float[2](0.0, 0.0));\n"
"const float49 f49_1 = float49(float[2](1.0, 0.0));\n"
"const float49 f49_e = float49(float[2](2.7182817,8.2548404e-8));\n"
"const float49 f49_log2 = float49(float[2](0.6931472,-1.9046542e-9));\n"
"const float49 f49_log10 = float49(float[2](2.3025851,-3.1975436e-8));\n"
"const float49 f49_2pi = float49(float[2](6.2831855,-1.7484555e-7));\n"
"const float49 f49_pi = float49(float[2](3.1415927,-8.742278e-8));\n"
"const float49 f49_3pi4 = float49(float[2](2.3561945,-5.9624403e-9));\n"
"const float49 f49_pi2 = float49(float[2](1.5707964,-4.371139e-8));\n"
"const float49 f49_pi4 = float49(float[2](0.7853982,-2.1855694e-8));\n"
"const float49 f49_pi16 = float49(float[2](0.19634955,-5.4639235e-9));\n"
"\n"
"const float f49_eps = 1.4210855e-14; \n"
"const float f49_min_normalized = 1.9721523e-31; \n"
"const float49 f49_max = float49(float[2](3.4028235e38, 2.0282408e31));\n"
"const float49 f49_safe_max = float49(float[2](3.401993e38, 2.0282408e31));\n"
"const int f49_ndigits = 13;\n"
"\n"
"/*********** Basic Functions ************/\n"
"/* Computes fl(a+b) and err(a+b).  Assumes |a| >= |b|. */\n"
"float quick_two_sum(float a, float b, out float err) {\n"
"  float s = EXACT(a + b);\n"
"  err = EXACT(b - EXACT(s - a));\n"
"  return s;\n"
"}\n"
"\n"
"/* Computes fl(a-b) and err(a-b).  Assumes |a| >= |b| */\n"
"float quick_two_diff(float a, float b, out float err) {\n"
"  float s = EXACT(a - b);\n"
"  err = EXACT(EXACT(a - s) - b);\n"
"  return s;\n"
"}\n"
"\n"
"/* Computes fl(a+b) and err(a+b).  */\n"
"float two_sum(float a, float b, out float err) {\n"
"  float s = EXACT(a + b);\n"
"  float bb = EXACT(s - a);\n"
"  err = EXACT(EXACT(a - EXACT(s - bb)) + EXACT(b - bb));\n"
"  return s;\n"
"}\n"
"\n"
"/* Computes fl(a-b) and err(a-b).  */\n"
"float two_diff(float a, float b, out float err) {\n"
"  float s = EXACT(a - b);\n"
"  float bb = EXACT(s - a);\n"
"  err = EXACT(EXACT(a - EXACT(s - bb)) - EXACT(b + bb));\n"
"  return s;\n"
"}\n"
"\n"
"#ifndef QD_FMS\n"
"/* Computes high word and lo word of a */\n"
"void split(float a, out float hi, out float lo) {\n"
"  float temp;\n"
"  if (a > _QD_SPLIT_THRESH || a < -_QD_SPLIT_THRESH) {\n"
"    a *= 3.7252902984619140625e-09;  \n"
"    temp = _QD_SPLITTER * a;\n"
"    hi = EXACT(temp - EXACT(temp - a));\n"
"    lo = EXACT(a - hi);\n"
"    hi *= 268435456.0;          \n"
"    lo *= 268435456.0;          \n"
"  } else {\n"
"    temp = _QD_SPLITTER * a;\n"
"    hi = EXACT(temp - EXACT(temp - a));\n"
"    lo = EXACT(a - hi);\n"
"  }\n"
"}\n"
"#endif\n"
"\n"
"/* Computes fl(a*b) and err(a*b). */\n"
"float two_prod(float a, float b, out float err) {\n"
"#ifdef QD_FMS\n"
"  float p = EXACT(a * b);\n"
"  err = QD_FMS(a, b, p);\n"
"  return p;\n"
"#else\n"
"  float a_hi, a_lo, b_hi, b_lo;\n"
"  float p = EXACT(a * b);\n"
"  split(a, a_hi, a_lo);\n"
"  split(b, b_hi, b_lo);\n"
"  err = EXACT(EXACT(EXACT(a_hi * b_hi) - p) + a_hi * b_lo + a_lo * b_hi) + a_lo * b_lo;\n"
"  return p;\n"
"#endif\n"
"}\n"
"\n"
"/* Computes fl(a*a) and err(a*a).  Faster than the above method. */\n"
"float two_sqr(float a, out float err) {\n"
"#ifdef QD_FMS\n"
"  float p = EXACT(a * a);\n"
"  err = QD_FMS(a, a, p);\n"
"  return p;\n"
"#else\n"
"  float hi, lo;\n"
"  float q = EXACT(a * a);\n"
"  split(a, hi, lo);\n"
"  err = EXACT(EXACT(EXACT(hi * hi) - q) + 2.0 * hi * lo) + lo * lo;\n"
"  return q;\n"
"#endif\n"
"}\n"
"\n"
"/* Computes the nearest integer to d. */\n"
"float nint(float d) {\n"
"  if (d == floor(d))\n"
"    return d;\n"
"  return floor(d + 0.5);\n"
"}\n"
"\n"
"/* Computes the truncated integer. */\n"
"float aint(float d) {\n"
"  return (d >= 0.0) ? floor(d) : ceil(d);\n"
"}\n"
"\n"
"/* These are provided to give consistent\n"
"   interface for float with float-float and quad-float. */\n"
"void sincosh(float t, out float sinh_t, out float cosh_t) {\n"
"  sinh_t = sinh(t);\n"
"  cosh_t = cosh(t);\n"
"}\n"
"\n"
"float sqr(float t) {\n"
"  return t * t;\n"
"}\n"
"\n"
"float to_float(float a) { return a; }\n"
"int    to_int(float a) { return int(a); }\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*\n"
" * src/dd_const.cc\n"
" *\n"
" * This work was supported by the Director, Office of Science, Division\n"
" * of Mathematical, Information, and Computational Sciences of the\n"
" * U.S. Department of Energy under contract number DE-AC03-76SF00098.\n"
" *\n"
" * Copyright (c) 2000-2007\n"
" */\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*\n"
" * include/dd_inline.h\n"
" *\n"
" * This work was supported by the Director, Office of Science, Division\n"
" * of Mathematical, Information, and Computational Sciences of the\n"
" * U.S. Department of Energy under contract number DE-AC03-76SF00098.\n"
" *\n"
" * Copyright (c) 2000-2001\n"
" *\n"
" * Contains small functions (suitable for inlining) in the float-float\n"
" * arithmetic package.\n"
" */\n"
"\n"
"/*********** Additions ************/\n"
"/* float-float = float + float */\n"
"float49 f49_add(float a, float b) {\n"
"  float s, e;\n"
"  s = two_sum(a, b, e);\n"
"  return float49_(s, e);\n"
"}\n"
"\n"
"/* float-float + float */\n"
"float49 add(const float49 a, float b) {\n"
"  float s1, s2;\n"
"  s1 = two_sum(a.x[0], b, s2);\n"
"  s2 = EXACT(s2 + a.x[1]);\n"
"  s1 = quick_two_sum(s1, s2, s2);\n"
"  return float49_(s1, s2);\n"
"}\n"
"\n"
"/* float-float + float-float */\n"
"float49 ieee_add(const float49 a, const float49 b) {\n"
"  /* This one satisfies IEEE style error bound,\n"
"     due to K. Briggs and W. Kahan.                   */\n"
"  float s1, s2, t1, t2;\n"
"\n"
"  s1 = two_sum(a.x[0], b.x[0], s2);\n"
"  t1 = two_sum(a.x[1], b.x[1], t2);\n"
"  s2 = EXACT(s2 + t1);\n"
"  s1 = quick_two_sum(s1, s2, s2);\n"
"  s2 = EXACT(s2 + t2);\n"
"  s1 = quick_two_sum(s1, s2, s2);\n"
"  return float49_(s1, s2);\n"
"}\n"
"\n"
"float49 sloppy_add(const float49 a, const float49 b) {\n"
"  /* This is the less accurate version ... obeys Cray-style\n"
"     error bound. */\n"
"  float s, e;\n"
"\n"
"  s = two_sum(a.x[0], b.x[0], e);\n"
"  e = EXACT(e + EXACT(a.x[1] + b.x[1]));\n"
"  s = quick_two_sum(s, e, e);\n"
"  return float49_(s, e);\n"
"}\n"
"\n"
"float49 add(const float49 a, const float49 b) {\n"
"#ifndef QD_IEEE_ADD\n"
"  return sloppy_add(a, b);\n"
"#else\n"
"  return ieee_add(a, b);\n"
"#endif\n"
"}\n"
"\n"
"/* float + float-float */\n"
"float49 add(float a, const float49 b) {\n"
"  return add(b, a);\n"
"}\n"
"\n"
"\n"
"/*********** Self-Additions ************/\n"
"/* float-float += float */\n"
"void add_set(inout float49 self, float a) {\n"
"  float s1, s2;\n"
"  s1 = two_sum(self.x[0], a, s2);\n"
"  s2 = EXACT(s2 + self.x[1]);\n"
"  self.x[0] = quick_two_sum(s1, s2, self.x[1]);\n"
"}\n"
"\n"
"/* float-float += float-float */\n"
"void add_set(inout float49 self, const float49 a) {\n"
"#ifndef QD_IEEE_ADD\n"
"  float s, e;\n"
"  s = two_sum(self.x[0], a.x[0], e);\n"
"  e = EXACT(e + self.x[1]);\n"
"  e = EXACT(e + a.x[1]);\n"
"  self.x[0] = quick_two_sum(s, e, self.x[1]);\n"
"#else\n"
"  float s1, s2, t1, t2;\n"
"  s1 = two_sum(self.x[0], a.x[0], s2);\n"
"  t1 = two_sum(self.x[1], a.x[1], t2);\n"
"  s2 = EXACT(s2 + t1);\n"
"  s1 = quick_two_sum(s1, s2, s2);\n"
"  s2 = EXACT(s2 + t2);\n"
"  self.x[0] = quick_two_sum(s1, s2, self.x[1]);\n"
"#endif\n"
"}\n"
"\n"
"/*********** Subtractions ************/\n"
"/* float-float = float - float */\n"
"float49 f49_sub(float a, float b) {\n"
"  float s, e;\n"
"  s = two_diff(a, b, e);\n"
"  return float49_(s, e);\n"
"}\n"
"\n"
"/* float-float - float */\n"
"float49 sub(const float49 a, float b) {\n"
"  float s1, s2;\n"
"  s1 = two_diff(a.x[0], b, s2);\n"
"  s2 = EXACT(s2 + a.x[1]);\n"
"  s1 = quick_two_sum(s1, s2, s2);\n"
"  return float49_(s1, s2);\n"
"}\n"
"\n"
"/* float-float - float-float */\n"
"float49 sub(const float49 a, const float49 b) {\n"
"#ifndef QD_IEEE_ADD\n"
"  float s, e;\n"
"  s = two_diff(a.x[0], b.x[0], e);\n"
"  e = EXACT(e + a.x[1]);\n"
"  e = EXACT(e - b.x[1]);\n"
"  s = quick_two_sum(s, e, e);\n"
"  return float49_(s, e);\n"
"#else\n"
"  float s1, s2, t1, t2;\n"
"  s1 = two_diff(a.x[0], b.x[0], s2);\n"
"  t1 = two_diff(a.x[1], b.x[1], t2);\n"
"  s2 = EXACT(s2 + t1);\n"
"  s1 = quick_two_sum(s1, s2, s2);\n"
"  s2 = EXACT(s2 + t2);\n"
"  s1 = quick_two_sum(s1, s2, s2);\n"
"  return float49_(s1, s2);\n"
"#endif\n"
"}\n"
"\n"
"/* float - float-float */\n"
"float49 sub(float a, const float49 b) {\n"
"  float s1, s2;\n"
"  s1 = two_diff(a, b.x[0], s2);\n"
"  s2 = EXACT(s2 - b.x[1]);\n"
"  s1 = quick_two_sum(s1, s2, s2);\n"
"  return float49_(s1, s2);\n"
"}\n"
"\n"
"/*********** Self-Subtractions ************/\n"
"/* float-float -= float */\n"
"void sub_set(inout float49 self, float a) {\n"
"  float s1, s2;\n"
"  s1 = two_diff(self.x[0], a, s2);\n"
"  s2 = EXACT(s2 + self.x[1]);\n"
"  self.x[0] = quick_two_sum(s1, s2, self.x[1]);\n"
"}\n"
"\n"
"/* float-float -= float-float */\n"
"void sub_set(inout float49 self, const float49 a) {\n"
"#ifndef QD_IEEE_ADD\n"
"  float s, e;\n"
"  s = two_diff(self.x[0], a.x[0], e);\n"
"  e = EXACT(e + self.x[1]);\n"
"  e = EXACT(e - a.x[1]);\n"
"  self.x[0] = quick_two_sum(s, e, self.x[1]);\n"
"#else\n"
"  float s1, s2, t1, t2;\n"
"  s1 = two_diff(self.x[0], a.x[0], s2);\n"
"  t1 = two_diff(self.x[1], a.x[1], t2);\n"
"  s2 = EXACT(s2 + t1);\n"
"  s1 = quick_two_sum(s1, s2, s2);\n"
"  s2 = EXACT(s2 + t2);\n"
"  self.x[0] = quick_two_sum(s1, s2, self.x[1]);\n"
"#endif\n"
"}\n"
"\n"
"/*********** Unary Minus ***********/\n"
"float49 neg(const float49 a) {\n"
"  return float49_(-a.x[0], -a.x[1]);\n"
"}\n"
"\n"
"/*********** Multiplications ************/\n"
"/* float-float = float * float */\n"
"float49 f49_mul(float a, float b) {\n"
"  float p, e;\n"
"  p = two_prod(a, b, e);\n"
"  return float49_(p, e);\n"
"}\n"
"\n"
"/* float-float * (2.0 ^ exp) */\n"
"float49 ldexp(const float49 a, int exp) {\n"
"  return float49_(ldexp(a.x[0], exp), ldexp(a.x[1], exp));\n"
"}\n"
"\n"
"/* float-float * float,  where float is a power of 2. */\n"
"float49 mul_pwr2(const float49 a, float b) {\n"
"  return float49_(a.x[0] * b, a.x[1] * b);\n"
"}\n"
"\n"
"/* float-float * float */\n"
"float49 mul(const float49 a, float b) {\n"
"  float p1, p2;\n"
"\n"
"  p1 = two_prod(a.x[0], b, p2);\n"
"  p2 = EXACT(p2 + EXACT(a.x[1] * b));\n"
"  p1 = quick_two_sum(p1, p2, p2);\n"
"  return float49_(p1, p2);\n"
"}\n"
"\n"
"/* float-float * float-float */\n"
"float49 mul(const float49 a, const float49 b) {\n"
"  float p1, p2;\n"
"\n"
"  p1 = two_prod(a.x[0], b.x[0], p2);\n"
"  p2 = EXACT(p2 + EXACT(a.x[0] * b.x[1] + a.x[1] * b.x[0]));\n"
"  p1 = quick_two_sum(p1, p2, p2);\n"
"  return float49_(p1, p2);\n"
"}\n"
"\n"
"/* float * float-float */\n"
"float49 mul(float a, const float49 b) {\n"
"  return mul(b, a);\n"
"}\n"
"\n"
"/*********** Self-Multiplications ************/\n"
"/* float-float *= float */\n"
"void mul_set(inout float49 self, float a) {\n"
"  float p1, p2;\n"
"  p1 = two_prod(self.x[0], a, p2);\n"
"  p2 = EXACT(p2 + EXACT(self.x[1] * a));\n"
"  self.x[0] = quick_two_sum(p1, p2, self.x[1]);\n"
"}\n"
"\n"
"/* float-float *= float-float */\n"
"void mul_set(inout float49 self, const float49 a) {\n"
"  float p1, p2;\n"
"  p1 = two_prod(self.x[0], a.x[0], p2);\n"
"  p2 = EXACT(p2 + EXACT(a.x[1] * self.x[0]));\n"
"  p2 = EXACT(p2 + EXACT(a.x[0] * self.x[1]));\n"
"  self.x[0] = quick_two_sum(p1, p2, self.x[1]);\n"
"}\n"
"\n"
"/*********** Divisions ************/\n"
"float49 f49_div(float a, float b) {\n"
"  float q1, q2;\n"
"  float p1, p2;\n"
"  float s, e;\n"
"\n"
"  q1 = EXACT(a / b);\n"
"\n"
"  /* Compute  a - q1 * b */\n"
"  p1 = two_prod(q1, b, p2);\n"
"  s = two_diff(a, p1, e);\n"
"  e = EXACT(e - p2);\n"
"\n"
"  /* get next approximation */\n"
"  q2 = EXACT(EXACT(s + e) / b);\n"
"\n"
"  s = quick_two_sum(q1, q2, e);\n"
"\n"
"  return float49_(s, e);\n"
"}\n"
"\n"
"/* float-float / float */\n"
"float49 div(const float49 a, float b) {\n"
"\n"
"  float q1, q2;\n"
"  float p1, p2;\n"
"  float s, e;\n"
"  float49 r;\n"
"\n"
"  q1 = EXACT(a.x[0] / b);   /* approximate quotient. */\n"
"\n"
"  /* Compute  this - q1 * d */\n"
"  p1 = two_prod(q1, b, p2);\n"
"  s = two_diff(a.x[0], p1, e);\n"
"  e = EXACT(e + a.x[1]);\n"
"  e = EXACT(e - p2);\n"
"\n"
"  /* get next approximation. */\n"
"  q2 = EXACT(EXACT(s + e) / b);\n"
"\n"
"  /* renormalize */\n"
"  r.x[0] = quick_two_sum(q1, q2, r.x[1]);\n"
"\n"
"  return r;\n"
"}\n"
"\n"
"float49 sloppy_div(const float49 a, const float49 b) {\n"
"  float s1, s2;\n"
"  float q1, q2;\n"
"  float49 r;\n"
"\n"
"  q1 = EXACT(a.x[0] / b.x[0]);  /* approximate quotient */\n"
"\n"
"  /* compute  this - q1 * dd */\n"
"  r = mul(b, q1);\n"
"  s1 = two_diff(a.x[0], r.x[0], s2);\n"
"  s2 = EXACT(s2 - r.x[1]);\n"
"  s2 = EXACT(s2 + a.x[1]);\n"
"\n"
"  /* get next approximation */\n"
"  q2 = EXACT(EXACT(s1 + s2) / b.x[0]);\n"
"\n"
"  /* renormalize */\n"
"  r.x[0] = quick_two_sum(q1, q2, r.x[1]);\n"
"  return r;\n"
"}\n"
"\n"
"float49 accurate_div(const float49 a, const float49 b) {\n"
"  float q1, q2, q3;\n"
"  float49 r;\n"
"\n"
"  q1 = EXACT(a.x[0] / b.x[0]);  /* approximate quotient */\n"
"\n"
"  r = sub(a, mul(q1, b));\n"
"\n"
"  q2 = EXACT(r.x[0] / b.x[0]);\n"
"  sub_set(r, mul(q2, b));\n"
"\n"
"  q3 = EXACT(r.x[0] / b.x[0]);\n"
"\n"
"  q1 = quick_two_sum(q1, q2, q2);\n"
"  r = add(float49_(q1, q2), q3);\n"
"  return r;\n"
"}\n"
"\n"
"/* float-float / float-float */\n"
"float49 div(const float49 a, const float49 b) {\n"
"#ifdef QD_SLOPPY_DIV\n"
"  return sloppy_div(a, b);\n"
"#else\n"
"  return accurate_div(a, b);\n"
"#endif\n"
"}\n"
"\n"
"/* float / float-float */\n"
"float49 div(float a, const float49 b) {\n"
"  return div(float49_(a), b);\n"
"}\n"
"\n"
"float49 inv(float49 a) {\n"
"  return div(1.0, a);\n"
"}\n"
"\n"
"/*********** Self-Divisions ************/\n"
"/* float-float /= float */\n"
"void div_set(inout float49 self, float a) {\n"
"  self = div(self, a);\n"
"}\n"
"\n"
"/* float-float /= float-float */\n"
"void div_set(inout float49 self, const float49 a) {\n"
"  self = div(self, a);\n"
"}\n"
"\n"
"/*********** Squaring **********/\n"
"float49 sqr(const float49 a) {\n"
"  float p1, p2;\n"
"  float s1, s2;\n"
"  p1 = two_sqr(a.x[0], p2);\n"
"  p2 = EXACT(p2 + EXACT(2.0 * a.x[0] * a.x[1]));\n"
"  p2 = EXACT(p2 + EXACT(a.x[1] * a.x[1]));\n"
"  s1 = quick_two_sum(p1, p2, s2);\n"
"  return float49_(s1, s2);\n"
"}\n"
"\n"
"float49 f49_sqr(float a) {\n"
"  float p1, p2;\n"
"  p1 = two_sqr(a, p2);\n"
"  return float49_(p1, p2);\n"
"}\n"
"\n"
"/*********** Micellaneous ************/\n"
"/*  this == 0 */\n"
"bool is_zero(const float49 self) {\n"
"  return (self.x[0] == 0.0);\n"
"}\n"
"\n"
"/*  this == 1 */\n"
"bool is_one(const float49 self) {\n"
"  return (self.x[0] == 1.0 && self.x[1] == 0.0);\n"
"}\n"
"\n"
"/*  this > 0 */\n"
"bool is_positive(const float49 self) {\n"
"  return (self.x[0] > 0.0);\n"
"}\n"
"\n"
"/* this < 0 */\n"
"bool is_negative(const float49 self) {\n"
"  return (self.x[0] < 0.0);\n"
"}\n"
"\n"
"/* Absolute value */\n"
"float49 abs(const float49 a) {\n"
"  return (a.x[0] < 0.0) ? neg(a) : a;\n"
"}\n"
"\n"
"float49 fabs(const float49 a) {\n"
"  return abs(a);\n"
"}\n"
"\n"
"\n"
"/* Computes the n-th power of a float-float number.\n"
"   NOTE:  0^0 causes an error.                         */\n"
"float49 npwr(const float49 a, int n) {\n"
"\n"
"  if (n == 0) {\n"
"    if (is_zero(a)) {\n"
"      return f49_nan;\n"
"    }\n"
"    return f49_1;\n"
"  }\n"
"\n"
"  float49 r = a;\n"
"  float49 s = f49_1;\n"
"  int N = abs(n);\n"
"\n"
"  if (N > 1) {\n"
"    /* Use binary exponentiation */\n"
"    while (N > 0) {\n"
"      if (N % 2 == 1) {\n"
"        mul_set(s, r);\n"
"      }\n"
"      N /= 2;\n"
"      if (N > 0)\n"
"        r = sqr(r);\n"
"    }\n"
"  } else {\n"
"    s = r;\n"
"  }\n"
"\n"
"  /* Compute the reciprocal if n is negative. */\n"
"  if (n < 0)\n"
"    return inv(s);\n"
"\n"
"  return s;\n"
"}\n"
"\n"
"/********** Exponentiation **********/\n"
"float49 pow(const float49 a, int n) {\n"
"  return npwr(a, n);\n"
"}\n"
"\n"
"\n"
"/*********** Assignments ************/\n"
"/* float-float = float */\n"
"void set(out float49 self, float a) {\n"
"  self.x[0] = a;\n"
"  self.x[1] = 0.0;\n"
"}\n"
"\n"
"/*********** Equality Comparisons ************/\n"
"/* float-float == float */\n"
"bool eq(const float49 a, float b) {\n"
"  return (a.x[0] == b && a.x[1] == 0.0);\n"
"}\n"
"\n"
"/* float-float == float-float */\n"
"bool eq(const float49 a, const float49 b) {\n"
"  return (a.x[0] == b.x[0] && a.x[1] == b.x[1]);\n"
"}\n"
"\n"
"/* float == float-float */\n"
"bool eq(float a, const float49 b) {\n"
"  return (a == b.x[0] && b.x[1] == 0.0);\n"
"}\n"
"\n"
"/*********** Greater-Than Comparisons ************/\n"
"/* float-float > float */\n"
"bool gt(const float49 a, float b) {\n"
"  return (a.x[0] > b || (a.x[0] == b && a.x[1] > 0.0));\n"
"}\n"
"\n"
"/* float-float > float-float */\n"
"bool gt(const float49 a, const float49 b) {\n"
"  return (a.x[0] > b.x[0] || (a.x[0] == b.x[0] && a.x[1] > b.x[1]));\n"
"}\n"
"\n"
"/* float > float-float */\n"
"bool gt(float a, const float49 b) {\n"
"  return (a > b.x[0] || (a == b.x[0] && b.x[1] < 0.0));\n"
"}\n"
"\n"
"/*********** Less-Than Comparisons ************/\n"
"/* float-float < float */\n"
"bool lt(const float49 a, float b) {\n"
"  return (a.x[0] < b || (a.x[0] == b && a.x[1] < 0.0));\n"
"}\n"
"\n"
"/* float-float < float-float */\n"
"bool lt(const float49 a, const float49 b) {\n"
"  return (a.x[0] < b.x[0] || (a.x[0] == b.x[0] && a.x[1] < b.x[1]));\n"
"}\n"
"\n"
"/* float < float-float */\n"
"bool lt(float a, const float49 b) {\n"
"  return (a < b.x[0] || (a == b.x[0] && b.x[1] > 0.0));\n"
"}\n"
"\n"
"/*********** Greater-Than-Or-Equal-To Comparisons ************/\n"
"/* float-float >= float */\n"
"bool ge(const float49 a, float b) {\n"
"  return (a.x[0] > b || (a.x[0] == b && a.x[1] >= 0.0));\n"
"}\n"
"\n"
"/* float-float >= float-float */\n"
"bool ge(const float49 a, const float49 b) {\n"
"  return (a.x[0] > b.x[0] || (a.x[0] == b.x[0] && a.x[1] >= b.x[1]));\n"
"}\n"
"\n"
"/*********** Less-Than-Or-Equal-To Comparisons ************/\n"
"/* float-float <= float */\n"
"bool le(const float49 a, float b) {\n"
"  return (a.x[0] < b || (a.x[0] == b && a.x[1] <= 0.0));\n"
"}\n"
"\n"
"/* float-float <= float-float */\n"
"bool le(const float49 a, const float49 b) {\n"
"  return (a.x[0] < b.x[0] || (a.x[0] == b.x[0] && a.x[1] <= b.x[1]));\n"
"}\n"
"\n"
"/* float <= float-float */\n"
"bool le(float a, const float49 b) {\n"
"  return ge(b, a);\n"
"}\n"
"\n"
"/* float >= float-float */\n"
"bool ge(float a, const float49 b) {\n"
"  return le(b, a);\n"
"}\n"
"\n"
"/*********** Not-Equal-To Comparisons ************/\n"
"/* float-float != float */\n"
"bool ne(const float49 a, float b) {\n"
"  return (a.x[0] != b || a.x[1] != 0.0);\n"
"}\n"
"\n"
"/* float-float != float-float */\n"
"bool ne(const float49 a, const float49 b) {\n"
"  return (a.x[0] != b.x[0] || a.x[1] != b.x[1]);\n"
"}\n"
"\n"
"/* float != float-float */\n"
"bool ne(float a, const float49 b) {\n"
"  return (a != b.x[0] || b.x[1] != 0.0);\n"
"}\n"
"\n"
"\n"
"float49 max(float a, const float49 b)\n"
"{\n"
"  if (gt(a, b))\n"
"  {\n"
"    return float49_(a);\n"
"  }\n"
"  else\n"
"  {\n"
"    return b;\n"
"  }\n"
"}\n"
"\n"
"float49 max(const float49 b, float a)\n"
"{\n"
"  if (gt(a, b))\n"
"  {\n"
"    return float49_(a);\n"
"  }\n"
"  else\n"
"  {\n"
"    return b;\n"
"  }\n"
"}\n"
"\n"
"float49 max(const float49 a, const float49 b)\n"
"{\n"
"  if (gt(a, b))\n"
"  {\n"
"    return a;\n"
"  }\n"
"  else\n"
"  {\n"
"    return b;\n"
"  }\n"
"}\n"
"\n"
"/* Round to Nearest integer */\n"
"float49 nint(const float49 a) {\n"
"  float hi = nint(a.x[0]);\n"
"  float lo;\n"
"\n"
"  if (hi == a.x[0]) {\n"
"    /* High word is an integer already.  Round the low word.*/\n"
"    lo = nint(a.x[1]);\n"
"\n"
"    /* Renormalize. This is needed if x[0] = some integer, x[1] = 1/2.*/\n"
"    hi = quick_two_sum(hi, lo, lo);\n"
"  } else {\n"
"    /* High word is not an integer. */\n"
"    lo = 0.0;\n"
"    if (abs(hi-a.x[0]) == 0.5 && a.x[1] < 0.0) {\n"
"      /* There is a tie in the high word, consult the low word\n"
"         to break the tie. */\n"
"      hi -= 1.0;      /* NOTE: This does not cause INEXACT. */\n"
"    }\n"
"  }\n"
"\n"
"  return float49_(hi, lo);\n"
"}\n"
"\n"
"float49 floor(const float49 a) {\n"
"  float hi = floor(a.x[0]);\n"
"  float lo = 0.0;\n"
"\n"
"  if (hi == a.x[0]) {\n"
"    /* High word is integer already.  Round the low word. */\n"
"    lo = floor(a.x[1]);\n"
"    hi = quick_two_sum(hi, lo, lo);\n"
"  }\n"
"\n"
"  return float49_(hi, lo);\n"
"}\n"
"\n"
"float49 ceil(const float49 a) {\n"
"  float hi = ceil(a.x[0]);\n"
"  float lo = 0.0;\n"
"\n"
"  if (hi == a.x[0]) {\n"
"    /* High word is integer already.  Round the low word. */\n"
"    lo = ceil(a.x[1]);\n"
"    hi = quick_two_sum(hi, lo, lo);\n"
"  }\n"
"\n"
"  return float49_(hi, lo);\n"
"}\n"
"\n"
"float49 aint(const float49 a) {\n"
"  return (a.x[0] >= 0.0) ? floor(a) : ceil(a);\n"
"}\n"
"\n"
"/********** Remainder **********/\n"
"float49 drem(const float49 a, const float49 b) {\n"
"  float49 n = nint(div(a, b));\n"
"  return sub(a, mul(n, b));\n"
"}\n"
"\n"
"float49 divrem(const float49 a, const float49 b, out float49 r) {\n"
"  float49 n = nint(div(a, b));\n"
"  r = sub(a, mul(n, b));\n"
"  return n;\n"
"}\n"
"\n"
"/* Cast to float. */\n"
"float to_float(const float49 a) {\n"
"  return a.x[0];\n"
"}\n"
"\n"
"/* Cast to int. */\n"
"int to_int(const float49 a) {\n"
"  return int(a.x[0]);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*\n"
" * src/dd_real.cc\n"
" *\n"
" * This work was supported by the Director, Office of Science, Division\n"
" * of Mathematical, Information, and Computational Sciences of the\n"
" * U.S. Department of Energy under contract number DE-AC03-76SF00098.\n"
" *\n"
" * Copyright (c) 2000-2007\n"
" *\n"
" * Contains implementation of non-inlined functions of float-float\n"
" * package.  Inlined functions are found in dd_inline.h (in include directory).\n"
" */\n"
"\n"
"/* Computes the square root of the float-float number dd.\n"
"   NOTE: dd must be a non-negative number.                   */\n"
"float49 sqrt(const float49 a) {\n"
"  /* Strategy:  Use Karp's trick:  if x is an approximation\n"
"     to sqrt(a), then\n"
"\n"
"        sqrt(a) = a*x + [a - (a*x)^2] * x / 2   (approx)\n"
"\n"
"     The approximation is accurate to twice the accuracy of x.\n"
"     Also, the multiplication (a*x) and [-]*x can be done with\n"
"     only half the precision.\n"
"  */\n"
"\n"
"  if (is_zero(a))\n"
"    return f49_0;\n"
"\n"
"  if (is_negative(a)) {\n"
"    return f49_nan;\n"
"  }\n"
"\n"
"  float x = EXACT(1.0 / sqrt(a.x[0]));\n"
"  float ax = EXACT(a.x[0] * x);\n"
"  return f49_add(ax, sub(a, f49_sqr(ax)).x[0] * (x * 0.5));\n"
"}\n"
"\n"
"/* Computes the square root of a float in float-float precision.\n"
"   NOTE: d must not be negative.                                   */\n"
"float49 f49_sqrt(float d) {\n"
"  return sqrt(float49_(d));\n"
"}\n"
"\n"
"/* Computes the n-th root of the float-float number a.\n"
"   NOTE: n must be a positive integer.\n"
"   NOTE: If n is even, then a must not be negative.       */\n"
"float49 nroot(const float49 a, int n) {\n"
"  /* Strategy:  Use Newton iteration for the function\n"
"\n"
"          f(x) = x^(-n) - a\n"
"\n"
"     to find its root a^{-1/n}.  The iteration is thus\n"
"\n"
"          x' = x + x * (1 - a * x^n) / n\n"
"\n"
"     which converges quadratically.  We can then find\n"
"    a^{1/n} by taking the reciprocal.\n"
"  */\n"
"\n"
"  if (n <= 0) {\n"
"    return f49_nan;\n"
"  }\n"
"\n"
"  if (n%2 == 0 && is_negative(a)) {\n"
"    return f49_nan;\n"
"  }\n"
"\n"
"  if (n == 1) {\n"
"    return a;\n"
"  }\n"
"  if (n == 2) {\n"
"    return sqrt(a);\n"
"  }\n"
"\n"
"  if (is_zero(a))\n"
"    return f49_0;\n"
"\n"
"  /* Note  a^{-1/n} = exp(-log(a)/n) */\n"
"  float49 r = abs(a);\n"
"  float49 x; set(x, exp(-log(r.x[0]) / n));\n"
"\n"
"  /* Perform Newton's iteration. */\n"
"  add_set(x, div(mul(x, sub(1.0, mul(r, npwr(x, n)))), float(n)));\n"
"  if (a.x[0] < 0.0)\n"
"    x = neg(x);\n"
"  return inv(x);\n"
"}\n"
"\n"
"\n"
"const int n_inv_fact = 15;\n"
"const float49 inv_fact[n_inv_fact] = float49[n_inv_fact]\n"
"  ( float49(float[2](0.16666667,-4.967054e-9))\n"
"  , float49(float[2](4.1666668e-2,-1.2417635e-9))\n"
"  , float49(float[2](8.333334e-3,-4.346172e-10))\n"
"  , float49(float[2](1.3888889e-3,-3.3631094e-11))\n"
"  , float49(float[2](1.984127e-4,-2.7255969e-12))\n"
"  , float49(float[2](2.4801588e-5,-3.406996e-13))\n"
"  , float49(float[2](2.7557319e-6,3.7935712e-14))\n"
"  , float49(float[2](2.755732e-7,-7.575112e-15))\n"
"  , float49(float[2](2.5052108e-8,4.417623e-16))\n"
"  , float49(float[2](2.0876756e-9,1.108284e-16))\n"
"  , float49(float[2](1.6059044e-10,-5.3525265e-18))\n"
"  , float49(float[2](1.1470745e-11,2.3722077e-19))\n"
"  , float49(float[2](7.6471636e-13,1.22007105e-20))\n"
"  , float49(float[2](4.7794773e-14,7.625444e-22))\n"
"  , float49(float[2](2.8114574e-15,-1.0462085e-22))\n"
"  );\n"
"\n"
"/* Exponential.  Computes exp(x) in float-float precision. */\n"
"float49 exp(const float49 a) {\n"
"  /* Strategy:  We first reduce the size of x by noting that\n"
"\n"
"          exp(kr + m * log(2)) = 2^m * exp(r)^k\n"
"\n"
"     where m and k are integers.  By choosing m appropriately\n"
"     we can make |kr| <= log(2) / 2 = 0.347.  Then exp(r) is\n"
"     evaluated using the familiar Taylor series.  Reducing the\n"
"     argument substantially speeds up the convergence.       */\n"
"\n"
"  const float k = 512.0;\n"
"  const float inv_k = 1.0 / k;\n"
"\n"
"  if (a.x[0] <= -709.0)\n"
"    return f49_0;\n"
"\n"
"  if (a.x[0] >=  709.0)\n"
"    return f49_inf;\n"
"\n"
"  if (is_zero(a))\n"
"    return f49_1;\n"
"\n"
"  if (is_one(a))\n"
"    return f49_e;\n"
"\n"
"  float m = floor(a.x[0] / f49_log2.x[0] + 0.5);\n"
"  float49 r = mul_pwr2(sub(a, mul(f49_log2, m)), inv_k);\n"
"  float49 s, t, p;\n"
"\n"
"  p = sqr(r);\n"
"  s = add(r, mul_pwr2(p, 0.5));\n"
"  mul_set(p, r);\n"
"  t = mul(p, inv_fact[0]);\n"
"  int i = 0;\n"
"  do {\n"
"    add_set(s, t);\n"
"    mul_set(p, r);\n"
"    ++i;\n"
"    t = mul(p, inv_fact[i]);\n"
"  } while (abs(to_float(t)) > inv_k * f49_eps && i < 5);\n"
"\n"
"  add_set(s, t);\n"
"\n"
"  s = add(mul_pwr2(s, 2.0), sqr(s));\n"
"  s = add(mul_pwr2(s, 2.0), sqr(s));\n"
"  s = add(mul_pwr2(s, 2.0), sqr(s));\n"
"  s = add(mul_pwr2(s, 2.0), sqr(s));\n"
"  s = add(mul_pwr2(s, 2.0), sqr(s));\n"
"  s = add(mul_pwr2(s, 2.0), sqr(s));\n"
"  s = add(mul_pwr2(s, 2.0), sqr(s));\n"
"  s = add(mul_pwr2(s, 2.0), sqr(s));\n"
"  s = add(mul_pwr2(s, 2.0), sqr(s));\n"
"  add_set(s, 1.0);\n"
"\n"
"  return ldexp(s, int(m));\n"
"}\n"
"\n"
"/* Logarithm.  Computes log(x) in float-float precision.\n"
"   This is a natural logarithm (i.e., base e).            */\n"
"float49 log(const float49 a) {\n"
"  /* Strategy.  The Taylor series for log converges much more\n"
"     slowly than that of exp, due to the lack of the factorial\n"
"     term in the denominator.  Hence this routine instead tries\n"
"     to determine the root of the function\n"
"\n"
"         f(x) = exp(x) - a\n"
"\n"
"     using Newton iteration.  The iteration is given by\n"
"\n"
"         x' = x - f(x)/f'(x)\n"
"            = x - (1 - a * exp(-x))\n"
"            = x + a * exp(-x) - 1.\n"
"\n"
"     Only one iteration is needed, since Newton's iteration\n"
"     approximately doubles the number of digits per iteration. */\n"
"\n"
"  if (is_one(a)) {\n"
"    return f49_0;\n"
"  }\n"
"\n"
"  if (a.x[0] <= 0.0) {\n"
"    return f49_nan;\n"
"  }\n"
"\n"
"  float49 x;\n"
"  set(x, log(a.x[0]));   /* Initial approximation */\n"
"\n"
"  x = sub(add(x, mul(a, exp(neg(x)))), 1.0);\n"
"  return x;\n"
"}\n"
"\n"
"float49 log10(const float49 a) {\n"
"  return div(log(a), f49_log10);\n"
"}\n"
"\n"
"float49 pow(const float49 a, const float49 b) {\n"
"  return exp(mul(b, log(a)));\n"
"}\n"
"\n"
"/* Table of sin(k * pi/16) and cos(k * pi/16). */\n"
"const float49 sin_table[4] = float49[4]\n"
"  ( float49(float[2](0.19509032,-1.6704715e-9))\n"
"  , float49(float[2](0.38268343,6.2233507e-9))\n"
"  , float49(float[2](0.55557024,-1.1769521e-8))\n"
"  , float49(float[2](0.70710677,1.21016175e-8))\n"
"  );\n"
"const float49 cos_table[4] = float49[4]\n"
"  ( float49(float[2](0.98078525,2.9739473e-8))\n"
"  , float49(float[2](0.9238795,2.830749e-8))\n"
"  , float49(float[2](0.8314696,1.6870263e-8))\n"
"  , float49(float[2](0.70710677,1.21016175e-8))\n"
"  );\n"
"\n"
"/* Computes sin(a) using Taylor series.\n"
"   Assumes |a| <= pi/32.                           */\n"
"float49 sin_taylor(const float49 a) {\n"
"  float thresh = 0.5 * abs(to_float(a)) * f49_eps;\n"
"  float49 r, s, t, x;\n"
"\n"
"  if (is_zero(a)) {\n"
"    return f49_0;\n"
"  }\n"
"\n"
"  int i = 0;\n"
"  x = neg(sqr(a));\n"
"  s = a;\n"
"  r = a;\n"
"  do {\n"
"    mul_set(r, x);\n"
"    t = mul(r, inv_fact[i]);\n"
"    add_set(s, t);\n"
"    i += 2;\n"
"  } while (i < n_inv_fact && abs(to_float(t)) > thresh);\n"
"\n"
"  return s;\n"
"}\n"
"\n"
"float49 cos_taylor(const float49 a) {\n"
"  const float thresh = 0.5 * f49_eps;\n"
"  float49 r, s, t, x;\n"
"\n"
"  if (is_zero(a)) {\n"
"    return f49_1;\n"
"  }\n"
"\n"
"  x = neg(sqr(a));\n"
"  r = x;\n"
"  s = add(1.0, mul_pwr2(r, 0.5));\n"
"  int i = 1;\n"
"  do {\n"
"    mul_set(r, x);\n"
"    t = mul(r, inv_fact[i]);\n"
"    add_set(s, t);\n"
"    i += 2;\n"
"  } while (i < n_inv_fact && abs(to_float(t)) > thresh);\n"
"\n"
"  return s;\n"
"}\n"
"\n"
"void sincos_taylor(const float49 a, out float49 sin_a, out float49 cos_a) {\n"
"  if (is_zero(a)) {\n"
"    set(sin_a, 0.0);\n"
"    set(cos_a, 1.0);\n"
"    return;\n"
"  }\n"
"\n"
"  sin_a = sin_taylor(a);\n"
"  cos_a = sqrt(sub(1.0, sqr(sin_a)));\n"
"}\n"
"\n"
"\n"
"float49 sin(const float49 a) {\n"
"\n"
"  /* Strategy.  To compute sin(x), we choose integers a, b so that\n"
"\n"
"       x = s + a * (pi/2) + b * (pi/16)\n"
"\n"
"     and |s| <= pi/32.  Using the fact that\n"
"\n"
"       sin(pi/16) = 0.5 * sqrt(2 - sqrt(2 + sqrt(2)))\n"
"\n"
"     we can compute sin(x) from sin(s), cos(s).  This greatly\n"
"     increases the convergence of the sine Taylor series. */\n"
"\n"
"  if (is_zero(a)) {\n"
"    return f49_0;\n"
"  }\n"
"\n"
"  \n"
"  float49 z = nint(div(a, f49_2pi));\n"
"  float49 r = sub(a, mul(f49_2pi, z));\n"
"\n"
"  \n"
"  float49 t;\n"
"  float q = floor(r.x[0] / f49_pi2.x[0] + 0.5);\n"
"  t = sub(r, mul(f49_pi2, q));\n"
"  int j = int(q);\n"
"  q = floor(t.x[0] / f49_pi16.x[0] + 0.5);\n"
"  sub_set(t, mul(f49_pi16, q));\n"
"  int k = int(q);\n"
"  int abs_k = abs(k);\n"
"\n"
"  if (j < -2 || j > 2) {\n"
"    return f49_nan;\n"
"  }\n"
"\n"
"  if (abs_k > 4) {\n"
"    return f49_nan;\n"
"  }\n"
"\n"
"  if (k == 0) {\n"
"    switch (j) {\n"
"      case 0:\n"
"        return sin_taylor(t);\n"
"      case 1:\n"
"        return cos_taylor(t);\n"
"      case -1:\n"
"        return neg(cos_taylor(t));\n"
"      default:\n"
"        return neg(sin_taylor(t));\n"
"    }\n"
"  }\n"
"\n"
"  float49 u = cos_table[abs_k-1];\n"
"  float49 v = sin_table[abs_k-1];\n"
"  float49 sin_t, cos_t;\n"
"  sincos_taylor(t, sin_t, cos_t);\n"
"  if (j == 0) {\n"
"    if (k > 0) {\n"
"      r = add(mul(u, sin_t), mul(v, cos_t));\n"
"    } else {\n"
"      r = sub(mul(u, sin_t), mul(v, cos_t));\n"
"    }\n"
"  } else if (j == 1) {\n"
"    if (k > 0) {\n"
"      r = sub(mul(u, cos_t), mul(v, sin_t));\n"
"    } else {\n"
"      r = add(mul(u, cos_t), mul(v, sin_t));\n"
"    }\n"
"  } else if (j == -1) {\n"
"    if (k > 0) {\n"
"      r = sub(mul(v, sin_t), mul(u, cos_t));\n"
"    } else if (k < 0) {\n"
"      r = neg(add(mul(u, cos_t), mul(v, sin_t)));\n"
"    }\n"
"  } else {\n"
"    if (k > 0) {\n"
"      r = neg(add(mul(u, sin_t), mul(v, cos_t)));\n"
"    } else {\n"
"      r = sub(mul(v, cos_t), mul(u, sin_t));\n"
"    }\n"
"  }\n"
"\n"
"  return r;\n"
"}\n"
"\n"
"float49 cos(const float49 a) {\n"
"\n"
"  if (is_zero(a)) {\n"
"    return f49_1;\n"
"  }\n"
"\n"
"  \n"
"  float49 z = nint(div(a, f49_2pi));\n"
"  float49 r = sub(a, mul(z, f49_2pi));\n"
"\n"
"  \n"
"  float49 t;\n"
"  float q = floor(r.x[0] / f49_pi2.x[0] + 0.5);\n"
"  t = sub(r, mul(f49_pi2, q));\n"
"  int j = int(q);\n"
"  q = floor(t.x[0] / f49_pi16.x[0] + 0.5);\n"
"  sub_set(t, mul(f49_pi16, q));\n"
"  int k = int(q);\n"
"  int abs_k = abs(k);\n"
"\n"
"  if (j < -2 || j > 2) {\n"
"    return f49_nan;\n"
"  }\n"
"\n"
"  if (abs_k > 4) {\n"
"    return f49_nan;\n"
"  }\n"
"\n"
"  if (k == 0) {\n"
"    switch (j) {\n"
"      case 0:\n"
"        return cos_taylor(t);\n"
"      case 1:\n"
"        return neg(sin_taylor(t));\n"
"      case -1:\n"
"        return sin_taylor(t);\n"
"      default:\n"
"        return neg(cos_taylor(t));\n"
"    }\n"
"  }\n"
"\n"
"  float49 sin_t, cos_t;\n"
"  sincos_taylor(t, sin_t, cos_t);\n"
"  float49 u = cos_table[abs_k-1];\n"
"  float49 v = sin_table[abs_k-1];\n"
"\n"
"  if (j == 0) {\n"
"    if (k > 0) {\n"
"      r = sub(mul(u, cos_t), mul(v, sin_t));\n"
"    } else {\n"
"      r = add(mul(u, cos_t), mul(v, sin_t));\n"
"    }\n"
"  } else if (j == 1) {\n"
"    if (k > 0) {\n"
"      r = neg(add(mul(u, sin_t), mul(v, cos_t)));\n"
"    } else {\n"
"      r = sub(mul(v, cos_t), mul(u, sin_t));\n"
"    }\n"
"  } else if (j == -1) {\n"
"    if (k > 0) {\n"
"      r = add(mul(u, sin_t), mul(v, cos_t));\n"
"    } else {\n"
"      r = sub(mul(u, sin_t), mul(v, cos_t));\n"
"    }\n"
"  } else {\n"
"    if (k > 0) {\n"
"      r = sub(mul(v, sin_t), mul(u, cos_t));\n"
"    } else {\n"
"      r = neg(add(mul(u, cos_t), mul(v, sin_t)));\n"
"    }\n"
"  }\n"
"\n"
"  return r;\n"
"}\n"
"\n"
"void sincos(const float49 a, out float49 sin_a, out float49 cos_a) {\n"
"\n"
"  if (is_zero(a)) {\n"
"    set(sin_a, 0.0);\n"
"    set(cos_a, 1.0);\n"
"    return;\n"
"  }\n"
"\n"
"  \n"
"  float49 z = nint(div(a, f49_2pi));\n"
"  float49 r = sub(a, mul(f49_2pi, z));\n"
"\n"
"  \n"
"  float49 t;\n"
"  float q = floor(r.x[0] / f49_pi2.x[0] + 0.5);\n"
"  t = sub(r, mul(f49_pi2, q));\n"
"  int j = int(q);\n"
"  int abs_j = abs(j);\n"
"  q = floor(t.x[0] / f49_pi16.x[0] + 0.5);\n"
"  sub_set(t, mul(f49_pi16, q));\n"
"  int k = int(q);\n"
"  int abs_k = abs(k);\n"
"\n"
"  if (abs_j > 2) {\n"
"    cos_a = sin_a = f49_nan;\n"
"    return;\n"
"  }\n"
"\n"
"  if (abs_k > 4) {\n"
"    cos_a = sin_a = f49_nan;\n"
"    return;\n"
"  }\n"
"\n"
"  float49 sin_t, cos_t;\n"
"  float49 s, c;\n"
"\n"
"  sincos_taylor(t, sin_t, cos_t);\n"
"\n"
"  if (abs_k == 0) {\n"
"    s = sin_t;\n"
"    c = cos_t;\n"
"  } else {\n"
"    float49 u = cos_table[abs_k-1];\n"
"    float49 v = sin_table[abs_k-1];\n"
"\n"
"    if (k > 0) {\n"
"      s = add(mul(u, sin_t), mul(v, cos_t));\n"
"      c = sub(mul(u, cos_t), mul(v, sin_t));\n"
"    } else {\n"
"      s = sub(mul(u, sin_t), mul(v, cos_t));\n"
"      c = add(mul(u, cos_t), mul(v, sin_t));\n"
"    }\n"
"  }\n"
"\n"
"  if (abs_j == 0) {\n"
"    sin_a = s;\n"
"    cos_a = c;\n"
"  } else if (j == 1) {\n"
"    sin_a = c;\n"
"    cos_a = neg(s);\n"
"  } else if (j == -1) {\n"
"    sin_a = neg(c);\n"
"    cos_a = s;\n"
"  } else {\n"
"    sin_a = neg(s);\n"
"    cos_a = neg(c);\n"
"  }\n"
"\n"
"}\n"
"\n"
"float49 atan(const float49 y, const float49 x) {\n"
"  /* Strategy: Instead of using Taylor series to compute\n"
"     arctan, we instead use Newton's iteration to solve\n"
"     the equation\n"
"\n"
"        sin(z) = y/r    or    cos(z) = x/r\n"
"\n"
"     where r = sqrt(x^2 + y^2).\n"
"     The iteration is given by\n"
"\n"
"        z' = z + (y - sin(z)) / cos(z)          (for equation 1)\n"
"        z' = z - (x - cos(z)) / sin(z)          (for equation 2)\n"
"\n"
"     Here, x and y are normalized so that x^2 + y^2 = 1.\n"
"     If |x| > |y|, then first iteration is used since the\n"
"     denominator is larger.  Otherwise, the second is used.\n"
"  */\n"
"\n"
"  if (is_zero(x)) {\n"
"\n"
"    if (is_zero(y)) {\n"
"      /* Both x and y is zero. */\n"
"      return f49_nan;\n"
"    }\n"
"\n"
"    return (is_positive(y)) ? f49_pi2 : neg(f49_pi2);\n"
"  } else if (is_zero(y)) {\n"
"    return (is_positive(x)) ? f49_0 : f49_pi;\n"
"  }\n"
"\n"
"  if (eq(x, y)) {\n"
"    return (is_positive(y)) ? f49_pi4 : neg(f49_3pi4);\n"
"  }\n"
"\n"
"  if (eq(x, neg(y))) {\n"
"    return (is_positive(y)) ? f49_3pi4 : neg(f49_pi4);\n"
"  }\n"
"\n"
"  float49 r = sqrt(add(sqr(x), sqr(y)));\n"
"  float49 xx = div(x, r);\n"
"  float49 yy = div(y, r);\n"
"\n"
"  /* Compute float precision approximation to atan. */\n"
"  float49 z; set(z, atan(to_float(y), to_float(x)));\n"
"  float49 sin_z, cos_z;\n"
"\n"
"  if (abs(xx.x[0]) > abs(yy.x[0])) {\n"
"    /* Use Newton iteration 1.  z' = z + (y - sin(z)) / cos(z)  */\n"
"    sincos(z, sin_z, cos_z);\n"
"    add_set(z, div(sub(yy, sin_z), cos_z));\n"
"  } else {\n"
"    /* Use Newton iteration 2.  z' = z - (x - cos(z)) / sin(z)  */\n"
"    sincos(z, sin_z, cos_z);\n"
"    sub_set(z, div(sub(xx, cos_z), sin_z));\n"
"  }\n"
"\n"
"  return z;\n"
"}\n"
"\n"
"float49 atan(const float49 a) {\n"
"  return atan(a, f49_1);\n"
"}\n"
"\n"
"float49 tan(const float49 a) {\n"
"  float49 s, c;\n"
"  sincos(a, s, c);\n"
"  return div(s, c);\n"
"}\n"
"\n"
"float49 asin(const float49 a) {\n"
"  float49 abs_a = abs(a);\n"
"\n"
"  if (gt(abs_a, 1.0)) {\n"
"    return f49_nan;\n"
"  }\n"
"\n"
"  if (is_one(abs_a)) {\n"
"    return (is_positive(a)) ? f49_pi2 : neg(f49_pi2);\n"
"  }\n"
"\n"
"  return atan(a, sqrt(sub(1.0, sqr(a))));\n"
"}\n"
"\n"
"float49 acos(const float49 a) {\n"
"  float49 abs_a = abs(a);\n"
"\n"
"  if (gt(abs_a, 1.0)) {\n"
"    return f49_nan;\n"
"  }\n"
"\n"
"  if (is_one(abs_a)) {\n"
"    return (is_positive(a)) ? f49_0 : f49_pi;\n"
"  }\n"
"\n"
"  return atan(sqrt(sub(1.0, sqr(a))), a);\n"
"}\n"
"\n"
"float49 sinh(const float49 a) {\n"
"  if (is_zero(a)) {\n"
"    return f49_0;\n"
"  }\n"
"\n"
"  if (gt(abs(a), 0.05)) {\n"
"    float49 ea = exp(a);\n"
"    return mul_pwr2(sub(ea, inv(ea)), 0.5);\n"
"  }\n"
"\n"
"  /* since a is small, using the above formula gives\n"
"     a lot of cancellation.  So use Taylor series.   */\n"
"  float49 s = a;\n"
"  float49 t = a;\n"
"  float49 r = sqr(t);\n"
"  float m = 1.0;\n"
"  float thresh = abs((to_float(a)) * f49_eps);\n"
"\n"
"  do {\n"
"    m += 2.0;\n"
"    mul_set(t, r);\n"
"    div_set(t, (m-1) * m);\n"
"\n"
"    add_set(s, t);\n"
"  } while (gt(abs(t), thresh));\n"
"\n"
"  return s;\n"
"\n"
"}\n"
"\n"
"float49 cosh(const float49 a) {\n"
"  if (is_zero(a)) {\n"
"    return f49_1;\n"
"  }\n"
"\n"
"  float49 ea = exp(a);\n"
"  return mul_pwr2(add(ea, inv(ea)), 0.5);\n"
"}\n"
"\n"
"float49 tanh(const float49 a) {\n"
"  if (is_zero(a)) {\n"
"    return f49_0;\n"
"  }\n"
"\n"
"  if (abs(to_float(a)) > 0.05) {\n"
"    float49 ea = exp(a);\n"
"    float49 inv_ea = inv(ea);\n"
"    return div(sub(ea, inv_ea), add(ea, inv_ea));\n"
"  } else {\n"
"    float49 s, c;\n"
"    s = sinh(a);\n"
"    c = sqrt(add(1.0, sqr(s)));\n"
"    return div(s, c);\n"
"  }\n"
"}\n"
"\n"
"void sincosh(const float49 a, out float49 s, out float49 c) {\n"
"  if (abs(to_float(a)) <= 0.05) {\n"
"    s = sinh(a);\n"
"    c = sqrt(add(1.0, sqr(s)));\n"
"  } else {\n"
"    float49 ea = exp(a);\n"
"    float49 inv_ea = inv(ea);\n"
"    s = mul_pwr2(sub(ea, inv_ea), 0.5);\n"
"    c = mul_pwr2(add(ea, inv_ea), 0.5);\n"
"  }\n"
"}\n"
"\n"
"float49 asinh(const float49 a) {\n"
"  return log(add(a, sqrt(add(sqr(a), 1.0))));\n"
"}\n"
"\n"
"float49 acosh(const float49 a) {\n"
"  if (lt(a, 1.0)) {\n"
"    return f49_nan;\n"
"  }\n"
"\n"
"  return log(add(a, sqrt(sub(sqr(a), 1.0))));\n"
"}\n"
"\n"
"float49 atanh(const float49 a) {\n"
"  if (ge(abs(a), 1.0)) {\n"
"    return f49_nan;\n"
"  }\n"
"\n"
"  return mul_pwr2(log(div(add(1.0, a), sub(1.0, a))), 0.5);\n"
"}\n"
"\n"
"float49 fmod(const float49 a, const float49 b) {\n"
"  float49 n = aint(div(a, b));\n"
"  return sub(a, mul(b, n));\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"const float nan = 0.0 / 0.0;\n"
"const float pi = 3.141592653;\n"
"\n"
"float hypot1(float x, float y) { return sqrt(x * x + y * y); }\n"
"float hypot2(float x, float y) { return x * x + y * y; }\n"
"\n"
"float srgb2lrgb(float s)\n"
"{\n"
"  if (s <= 0.04045)\n"
"    return s / 12.92;\n"
"  return pow((s + 0.055) / 1.055, 2.4);\n"
"}\n"
"\n"
"vec3 srgb2lrgb(vec3 s)\n"
"{\n"
"  return vec3(srgb2lrgb(s.x), srgb2lrgb(s.y), srgb2lrgb(s.z));\n"
"}\n"
"\n"
"float lrgb2srgb(float l)\n"
"{\n"
"  if (l <= 0.0031308)\n"
"    return l * 12.92;\n"
"  return 1.055  * pow(l, 1.0 / 2.4) - 0.055;\n"
"}\n"
"\n"
"vec3 lrgb2srgb(vec3 s)\n"
"{\n"
"  return vec3(lrgb2srgb(s.x), lrgb2srgb(s.y), lrgb2srgb(s.z));\n"
"}\n"
"\n"
"\n"
"vec3 hsv2rgb(vec3 c)\n"
"{\n"
"  vec4 K = vec4(1.0, 2.0 / 3.0, 1.0 / 3.0, 3.0);\n"
"  vec3 p = abs(fract(c.xxx + K.xyz) * 6.0 - K.www);\n"
"  vec3 rgb = c.z * mix(K.xxx, clamp(p - K.xxx, 0.0, 1.0), c.y);\n"
"  if (KFP_sRGB)\n"
"  {\n"
"    rgb = srgb2lrgb(rgb);\n"
"  }\n"
"  return rgb;\n"
"}\n"
"\n"
"vec3 KF_Palette(float ix)\n"
"{\n"
"  \n"
"  ix -= floor(ix);\n"
"  ix *= 1024.0;\n"
"  \n"
"  \n"
"  \n"
"  \n"
"  int m_nParts = textureSize(KFP_Palette, 0);\n"
"  vec3 c0, c1;\n"
"  {\n"
"    int i = int(floor(ix));\n"
"    float temp = float(i) * float(m_nParts) / 1024.0;\n"
"    int p = int(temp);\n"
"    int pn = (p + 1) % m_nParts;\n"
"    temp -= float(p);\n"
"    temp = sin((temp - 0.5) * pi) / 2.0 + 0.5;\n"
"    c0 = mix\n"
"      ( texelFetch(KFP_Palette, p, 0).rgb\n"
"      , texelFetch(KFP_Palette, pn, 0).rgb\n"
"      , temp\n"
"      );\n"
"  }\n"
"  if (KFP_Smooth)\n"
"  {\n"
"    int i = (int(floor(ix)) + 1) % 1024;\n"
"    float temp = float(i) * float(m_nParts) / 1024.0;\n"
"    int p = int(temp);\n"
"    int pn = (p + 1) % m_nParts;\n"
"    temp -= float(p);\n"
"    temp = sin((temp - 0.5) * pi) / 2.0 + 0.5;\n"
"    c1 = mix\n"
"      ( texelFetch(KFP_Palette, p, 0).rgb\n"
"      , texelFetch(KFP_Palette, pn, 0).rgb\n"
"      , temp\n"
"      );\n"
"    ix -= floor(ix);\n"
"    return mix(c0, c1, ix);\n"
"  }\n"
"  else\n"
"  {\n"
"    return c0;\n"
"  }\n"
"}\n"
"\n"
"uint hash(uint a)\n"
"{\n"
"  a = (a+0x7ed55d16u) + (a<<12);\n"
"  a = (a^0xc761c23cu) ^ (a>>19);\n"
"  a = (a+0x165667b1u) + (a<<5);\n"
"  a = (a+0xd3a2646cu) ^ (a<<9);\n"
"  a = (a+0xfd7046c5u) + (a<<3);\n"
"  a = (a^0xb55a4f09u) ^ (a>>16);\n"
"  return a;\n"
"}\n"
"\n"
"\n"
"float dither(int x, int y, int c)\n"
"{\n"
"  return float(hash(uint(x) + hash(uint(y) + hash(uint(c))))) / exp2(32.0);\n"
"}\n"
"\n"
"vec2 GetPixelOffset(ivec2 ix)\n"
"{\n"
"  float x = 0.0, y = 0.0;\n"
"  int c = int(KFP_JitterSeed);\n"
"  if (c != 0)\n"
"  {\n"
"    float s = KFP_JitterScale;\n"
"    float u = dither(ix.x, ix.y, 2 * c + 0);\n"
"    float v = dither(ix.x, ix.y, 2 * c + 1);\n"
"    switch (KFP_JitterShape)\n"
"    {\n"
"      default:\n"
"      case 0: \n"
"        {\n"
"          x = s * (u - 0.5);\n"
"          y = s * (v - 0.5);\n"
"        }\n"
"        break;\n"
"      case 1: \n"
"        {\n"
"          \n"
"          float r = 0.0 < u && u < 1.0 ? sqrt(-2.0 * log(u)) : 0.0;\n"
"          float t = 2.0 * 3.141592653589793 * v;\n"
"          s *= 0.5;\n"
"          x = s * r * cos(t);\n"
"          y = s * r * sin(t);\n"
"        }\n"
"        break;\n"
"    }\n"
"  }\n"
"  else\n"
"  {\n"
"    x = 0.0;\n"
"    y = 0.0;\n"
"  }\n"
"  return vec2(x, y);\n"
"}\n"
"\n"
"float49 cbrt(float49 a) { return nroot(a, 3); }\n"
"float49 wrap(float49 a) { return sub(a, floor(a)); }\n"
"\n"
"float49 float49_(uint a)\n"
"{\n"
"  float hi = float(a);\n"
"  float lo = float(a - uint(hi));\n"
"  return float49_(hi, lo);\n"
"}\n"
"float49 float49_(uint a, uint b) { return add(ldexp(float49_(a), 32), float49_(b)); }\n"
"float49 float49_(uint a, uint b, float c) { return add(float49_(a, b), c); }\n"
"\n"
"ivec2 Internal_TexCoord = Internal_TilePadding.yx + ivec2(Internal_TileSize.y - 1 - 2 * Internal_TilePadding.y - int(gl_FragCoord.y), int(gl_FragCoord.x));\n"
"ivec2 Internal_PixelCoord = Internal_TileOrigin.xy + ivec2(int(gl_FragCoord.x), Internal_TileSize.y - 1 - 2 * Internal_TilePadding.y - int(gl_FragCoord.y));\n"
"\n"
"uint    getN1 (ivec2 offset) { return texelFetch(Internal_N1,  Internal_TexCoord + offset.yx, 0).r; }\n"
"uint    getN0 (ivec2 offset) { return texelFetch(Internal_N0,  Internal_TexCoord + offset.yx, 0).r; }\n"
"float   getNF (ivec2 offset) { return texelFetch(Internal_NF,  Internal_TexCoord + offset.yx, 0).r; }\n"
"float   getT  (ivec2 offset) { return texelFetch(Internal_T,   Internal_TexCoord + offset.yx, 0).r; }\n"
"float   getDEX(ivec2 offset) { return texelFetch(Internal_DEX, Internal_TexCoord + offset.yx, 0).r; }\n"
"float   getDEY(ivec2 offset) { return texelFetch(Internal_DEY, Internal_TexCoord + offset.yx, 0).r; }\n"
"uint    getN1 (void) { return getN1 (ivec2(0, 0)); }\n"
"uint    getN0 (void) { return getN0 (ivec2(0, 0)); }\n"
"float   getNF (void) { return getNF (ivec2(0, 0)); }\n"
"float   getT  (void) { return getT  (ivec2(0, 0)); }\n"
"float   getDEX(void) { return getDEX(ivec2(0, 0)); }\n"
"float   getDEY(void) { return getDEY(ivec2(0, 0)); }\n"
"bool    getGlitch  (ivec2 offset) { return getNF(offset) < 0.0; }\n"
"bool    getInterior(ivec2 offset) { return uvec2(getN0(offset), getN1(offset)) == KFP_Iterations; }\n"
"float49 getN  (ivec2 offset) { return float49_(getN1(offset), getN0(offset), 1.0 - getNF(offset)); }\n"
"vec2    getDE (ivec2 offset) { return vec2(getDEX(offset), getDEY(offset)); }\n"
"bool    getGlitch  (void) { return getGlitch(ivec2(0, 0)); }\n"
"bool    getInterior(void) { return getInterior(ivec2(0, 0)); }\n"
"float49 getN  (void) { return getN (ivec2(0, 0)); }\n"
"vec2    getDE (void) { return getDE(ivec2(0, 0)); }\n"
"\n"
"bool inImage(ivec2 offset)\n"
"{\n"
"  ivec2 pixel = Internal_PixelCoord + offset;\n"
"  return 0 <= pixel.x && pixel.x < ImageSize.x &&\n"
"         0 <= pixel.y && pixel.y < ImageSize.y;\n"
"}\n"
"\n"
"vec2 getJitter(ivec2 offset)\n"
"{\n"
"  if (inImage(offset))\n"
"  {\n"
"    return GetPixelOffset(Internal_PixelCoord + offset);\n"
"  }\n"
"  else\n"
"  {\n"
"    return vec2(0.0, 0.0); \n"
"  }\n"
"}\n"
"\n"
"vec2 getJitter(void)\n"
"{\n"
"  return getJitter(ivec2(0, 0));\n"
"}\n"
"\n"
"vec2 getCoord(void)\n"
"{\n"
"  return vec2(Internal_TileOrigin.xy) + gl_FragCoord.xy;\n"
"}\n"
"\n"
"float getZoomLog2(void)\n"
"{\n"
"  return Internal_ZoomLog2;\n"
"}\n"
"\n"
"float getZoomLog2(ivec2 offset)\n"
"{\n"
"  return Internal_ZoomLog2;\n"
"}\n"
"\n"
"float49 getN3x3(inout mat3 p, inout mat3 px, inout mat3 py)\n"
"{\n"
"  \n"
"  float49 N = getN();\n"
"  for (int dj = -1; dj <= 1; ++dj)\n"
"  {\n"
"    for (int di = -1; di <= 1; ++di)\n"
"    {\n"
"      ivec2 offset = ivec2(di, dj);\n"
"      p[di + 1][dj + 1] = sub(getN(offset), N).x[0];\n"
"      vec2 delta = getJitter(offset);\n"
"      px[di + 1][dj + 1] = float(di) + delta.x;\n"
"      py[di + 1][dj + 1] = float(dj) + delta.y;\n"
"    }\n"
"  }\n"
"  \n"
"  \n"
"  p[1][1] *= 2.0;\n"
"  px[1][1] *= 2.0;\n"
"  py[1][1] *= 2.0;\n"
"  if (isnan(p[0][0])) {p[0][0] = p[1][1] - p[2][2];px[0][0] = px[1][1] - px[2][2];py[0][0] = py[1][1] - py[2][2];}\n"
"  if (isnan(p[0][1])) {p[0][1] = p[1][1] - p[2][1];px[0][1] = px[1][1] - px[2][1];py[0][1] = py[1][1] - py[2][1];}\n"
"  if (isnan(p[0][2])) {p[0][2] = p[1][1] - p[2][0];px[0][2] = px[1][1] - px[2][0];py[0][2] = py[1][1] - py[2][0];}\n"
"  if (isnan(p[1][0])) {p[1][0] = p[1][1] - p[1][2];px[1][0] = px[1][1] - px[1][2];py[1][0] = py[1][1] - py[1][2];}\n"
"  if (isnan(p[1][2])) {p[1][2] = p[1][1] - p[1][0];px[1][2] = px[1][1] - px[1][0];py[1][2] = py[1][1] - py[1][0];}\n"
"  if (isnan(p[2][0])) {p[2][0] = p[1][1] - p[0][2];px[2][0] = px[1][1] - px[0][2];py[2][0] = py[1][1] - py[0][2];}\n"
"  if (isnan(p[2][1])) {p[2][1] = p[1][1] - p[0][1];px[2][1] = px[1][1] - px[0][1];py[2][1] = py[1][1] - py[0][1];}\n"
"  if (isnan(p[2][2])) {p[2][2] = p[1][1] - p[0][0];px[2][2] = px[1][1] - px[0][0];py[2][2] = py[1][1] - py[0][0];}\n"
"  p[1][1] *= 0.5;\n"
"  px[1][1] *= 0.5;\n"
"  py[1][1] *= 0.5;\n"
"  return N;\n"
"}\n"
"\n"
"float KF_Traditional(mat3 p, mat3 px, mat3 py)\n"
"{\n"
"  \n"
"  float gx = (p[0][1] - p[1][1]) * 1.414 / hypot1(px[0][1] - px[1][1], py[0][1] - py[1][1]);\n"
"  float gy = (p[1][0] - p[1][1]) * 1.414 / hypot1(px[1][0] - px[1][1], py[1][0] - py[1][1]);\n"
"  float gu = (p[0][0] - p[1][1]) * 1.414 / hypot1(px[0][0] - px[1][1], py[0][0] - py[1][1]);\n"
"  float gv = (p[0][2] - p[1][1]) * 1.414 / hypot1(px[0][2] - px[1][1], py[0][2] - py[1][1]);\n"
"  float g = abs(gx) + abs(gy) + abs(gu) + abs(gv);\n"
"  return 1.0 / g;\n"
"}\n"
"\n"
"float KF_Traditional(void)\n"
"{\n"
"  mat3 p = mat3(nan, nan, nan, nan, nan, nan, nan, nan, nan);\n"
"  mat3 px = mat3(0.0);\n"
"  mat3 py = mat3(0.0);\n"
"  getN3x3(p, px, py);\n"
"  return KF_Traditional(p, px, py);\n"
"}\n"
"\n"
"float KF_Forward3x3(mat3 p, mat3 px, mat3 py)\n"
"{\n"
"  \n"
"  float gx0 = sqr(p[0][1] - p[1][1]) / hypot2(px[0][1] - px[1][1], py[0][1] - py[1][1]);\n"
"  float gx2 = sqr(p[2][1] - p[1][1]) / hypot2(px[2][1] - px[1][1], py[2][1] - py[1][1]);\n"
"  float gy0 = sqr(p[1][0] - p[1][1]) / hypot2(px[1][0] - px[1][1], py[1][0] - py[1][1]);\n"
"  float gy2 = sqr(p[1][2] - p[1][1]) / hypot2(px[1][2] - px[1][1], py[1][2] - py[1][1]);\n"
"  float gu0 = sqr(p[0][0] - p[1][1]) / hypot2(px[0][0] - px[1][1], py[0][0] - py[1][1]);\n"
"  float gu2 = sqr(p[2][2] - p[1][1]) / hypot2(px[2][2] - px[1][1], py[2][2] - py[1][1]);\n"
"  float gv0 = sqr(p[2][0] - p[1][1]) / hypot2(px[2][0] - px[1][1], py[2][0] - py[1][1]);\n"
"  float gv2 = sqr(p[0][2] - p[1][1]) / hypot2(px[0][2] - px[1][1], py[0][2] - py[1][1]);\n"
"  float g = sqrt(0.25 * (gx0 + gx2 + gy0 + gy2 + gu0 + gu2 + gv0 + gv2));\n"
"  return 1.0 / (g * 2.8284271247461903);\n"
"}\n"
"\n"
"float KF_Forward3x3(void)\n"
"{\n"
"  mat3 p = mat3(nan, nan, nan, nan, nan, nan, nan, nan, nan);\n"
"  mat3 px = mat3(0.0);\n"
"  mat3 py = mat3(0.0);\n"
"  getN3x3(p, px, py);\n"
"  return KF_Forward3x3(p, px, py);\n"
"}\n"
"\n"
"float KF_Central3x3(mat3 p, mat3 px, mat3 py)\n"
"{\n"
"  \n"
"  float gx = sqr(p[2][1] - p[0][1]) / hypot2(px[2][1] - px[0][1], py[2][1] - py[0][1]);\n"
"  float gy = sqr(p[1][2] - p[1][0]) / hypot2(px[1][2] - px[1][0], py[1][2] - py[1][0]);\n"
"  float g1 = sqr(p[2][2] - p[0][0]) / hypot2(px[2][2] - px[0][0], py[2][2] - py[0][0]);\n"
"  float g2 = sqr(p[0][2] - p[2][0]) / hypot2(px[0][2] - px[2][0], py[0][2] - py[2][0]);\n"
"  float g = sqrt(0.5 * (gx + gy + g1 + g2));\n"
"  return 1.0 / (g * 2.8284271247461903);\n"
"}\n"
"\n"
"float KF_Central3x3(void)\n"
"{\n"
"  mat3 p = mat3(nan, nan, nan, nan, nan, nan, nan, nan, nan);\n"
"  mat3 px = mat3(0.0);\n"
"  mat3 py = mat3(0.0);\n"
"  getN3x3(p, px, py);\n"
"  return KF_Central3x3(p, px, py);\n"
"}\n"
"\n"
"float KF_Diagonal2x2(mat3 p, mat3 px, mat3 py)\n"
"{\n"
"  \n"
"  if (KFP_JitterSeed == 0u)\n"
"  {\n"
"    float gu = sqr(p[0][0] - p[1][1]) / hypot2(px[0][0] - px[1][1], py[0][0] - py[1][1]);\n"
"    float gv = sqr(p[0][1] - p[1][0]) / hypot2(px[0][1] - px[1][0], py[0][1] - py[1][0]);\n"
"    float g = sqrt(gu + gv);\n"
"    return 1.0 / (g * 2.8284271247461903);\n"
"  }\n"
"  else\n"
"  {\n"
"    \n"
"    float nux = px[0][0] - px[1][1];\n"
"    float nuy = py[0][0] - py[1][1];\n"
"    float nvx = px[1][0] - px[0][1];\n"
"    float nvy = py[1][0] - py[0][1];\n"
"    float nu = hypot1(nux, nuy);\n"
"    float nv = hypot1(nvx, nvy);\n"
"    nux /= nu;\n"
"    nuy /= nu;\n"
"    nvx /= nv;\n"
"    nvy /= nv;\n"
"    float u = (p[0][0] - p[1][1]) / nu;\n"
"    float v = (p[1][0] - p[0][1]) / nv;\n"
"    float dotnunv = nux * nvx + nuy * nvy;\n"
"    float crossnunv = nux * nvy - nuy * nvx;\n"
"    float g = sqrt((u * u + v * v - 2 * u * v * dotnunv) / sqr(crossnunv));\n"
"    return 1.0 / (g * 2.8284271247461903);\n"
"  }\n"
"}\n"
"\n"
"float KF_Diagonal2x2(void)\n"
"{\n"
"  mat3 p = mat3(nan, nan, nan, nan, nan, nan, nan, nan, nan);\n"
"  mat3 px = mat3(0.0);\n"
"  mat3 py = mat3(0.0);\n"
"  getN3x3(p, px, py);\n"
"  return KF_Diagonal2x2(p, px, py);\n"
"}\n"
"\n"
"#if 0\n"
"            case Differences_LeastSquares3x3:\n"
"            {\n"
"              float gx = 0;\n"
"              float gy = 0;\n"
"              \n"
"              float g = hypot1(gx, gy);\n"
"              iter = float49_(g * 2.8284271247461903);\n"
"            }\n"
"            break;\n"
"            case Differences_LeastSquares2x2:\n"
"            {\n"
"              float gx = 0;\n"
"              float gy = 0;\n"
"              \n"
"              float g = hypot1(gx, gy);\n"
"              iter = float49_(g * 2.8284271247461903);\n"
"            }\n"
"            break;\n"
"#endif\n"
"\n"
"float KF_Laplacian3x3(mat3 p, mat3 px, mat3 py)\n"
"{\n"
"  float L = 0.0;\n"
"  L +=  1.0 * p[0][0];\n"
"  L +=  4.0 * p[0][1];\n"
"  L +=  1.0 * p[0][2];\n"
"  L +=  4.0 * p[1][0];\n"
"  L -= 20.0 * p[1][1];\n"
"  L +=  4.0 * p[1][2];\n"
"  L +=  1.0 * p[2][0];\n"
"  L +=  4.0 * p[2][1];\n"
"  L +=  1.0 * p[2][2];\n"
"  L /=  6.0;\n"
"#define INV_LOG_2 1.4426950408889634\n"
"  float g = sqrt(abs(L * INV_LOG_2));\n"
"#undef INV_LOG_2\n"
"  return 1.0 / (g * 2.8284271247461903);\n"
"}\n"
"\n"
"float KF_Laplacian3x3(void)\n"
"{\n"
"  mat3 p = mat3(nan, nan, nan, nan, nan, nan, nan, nan, nan);\n"
"  mat3 px = mat3(0.0);\n"
"  mat3 py = mat3(0.0);\n"
"  getN3x3(p, px, py);\n"
"  return KF_Laplacian3x3(p, px, py);\n"
"}\n"
"\n"
"float KF_Analytic(ivec2 offset)\n"
"{\n"
"  return length(getDE(offset));\n"
"}\n"
"\n"
"float KF_Analytic(void)\n"
"{\n"
"  return KF_Analytic(ivec2(0, 0));\n"
"}\n"
"\n"
"float KF_DE(int method)\n"
"{\n"
"  switch (method)\n"
"  {\n"
"    default:\n"
"    case Differences_Traditional: return KF_Traditional();\n"
"    case Differences_Forward3x3: return KF_Forward3x3();\n"
"    case Differences_Central3x3: return KF_Central3x3();\n"
"    case Differences_Diagonal2x2: return KF_Diagonal2x2();\n"
"#if 0\n"
"    case Differences_LeastSquares2x2: return KF_LeastSquares2x2();\n"
"    case Differences_LeastSquares3x3: return KF_LeastSquares3x3();\n"
"#endif\n"
"    case Differences_Laplacian3x3: return KF_Laplacian3x3();\n"
"    case Differences_Analytic: return KF_Analytic();\n"
"  }\n"
"  return 0.0;\n"
"}\n"
"\n"
"vec3 KF_InfiniteWaves(bool Smooth, float49 iter)\n"
"{\n"
"  float nH = 0.0, nS = 0.0, nB = 0.0;\n"
"  int nDR = 0, nDG = 0, nDB = 0;\n"
"  for (int i = 0; i < KFP_MultiWavesCount; i++){\n"
"    float nPeriod = float(KFP_MultiWaves[i].x);\n"
"    float g;\n"
"    if (Smooth)\n"
"      g = sin(2.0 * pi * wrap(div(iter, nPeriod * 2.0)).x[0]) / 2.0 + 0.5;\n"
"    else\n"
"      g = sin(2.0 * pi * wrap(div(floor(iter), nPeriod * 2.0)).x[0]) / 2.0 + 0.5;\n"
"    if (nPeriod < 0)\n"
"      g = -nPeriod / 100.0;\n"
"    int type = KFP_MultiWaves[i].z;\n"
"    if (type == 0){\n"
"      nH += g;\n"
"      nDR++;\n"
"    }\n"
"    if (type == 1){\n"
"      nS += g;\n"
"      nDG++;\n"
"    }\n"
"    if (type == 2){\n"
"      nB += g;\n"
"      nDB++;\n"
"    }\n"
"  }\n"
"  if (nDR > 0)\n"
"    nH /= float(nDR);\n"
"  if (nDG > 0)\n"
"    nS /= float(nDG);\n"
"  if (nDB > 0)\n"
"    nB /= float(nDB);\n"
"  return hsv2rgb(vec3(nH, nS, nB));\n"
"}\n"
"\n"
"vec2 KF_TextureWarp(float TexturePower, float TextureRatio, vec2 SlopeDir)\n"
"{\n"
"  mat3 p = mat3(nan, nan, nan, nan, nan, nan, nan, nan, nan);\n"
"  mat3 px = mat3(0.0);\n"
"  mat3 py = mat3(0.0);\n"
"  getN3x3(p, px, py);\n"
"  float nImgOffs = TexturePower / 64.0;\n"
"  float diffx = p[0][1] - p[1][1];\n"
"  float diffy = p[1][0] - p[1][1];\n"
"  float diff = dot(vec2(diffx, diffy), SlopeDir);\n"
"  diff  = 1.0 + diff;\n"
"  diffx = 1.0 + diffx;\n"
"  diffy = 1.0 + diffy;\n"
"  diff  = pow(diff,  TexturePower);\n"
"  diffx = pow(diffx, TexturePower);\n"
"  diffy = pow(diffy, TexturePower);\n"
"  float sx = 1.0;\n"
"  float  sy = 1.0;\n"
"  if (diff  <= 1.0) { diff  = 1.0 / diff; }\n"
"  if (diffx <= 1.0) { diffx = 1.0 / diffx; sx = -sx; }\n"
"  if (diffy <= 1.0) { diffy = 1.0 / diffy; sy = -sy; }\n"
"  diff  = (atan(diff)  - pi / 4.0) / (pi / 4.0);\n"
"  diffx = (atan(diffx) - pi / 4.0) / (pi / 4.0);\n"
"  diffy = (atan(diffy) - pi / 4.0) / (pi / 4.0);\n"
"  diff  *= TextureRatio / 100.0;\n"
"  diffx *= TextureRatio / 100.0;\n"
"  diffy *= TextureRatio / 100.0;\n"
"  float dx = nImgOffs + sx * TexturePower * diffx;\n"
"  float dy = nImgOffs - sy * TexturePower * diffy;\n"
"  return vec2(dx, dy);\n"
"}\n"
"\n"
"vec4 KF_Slopes(bool analytic, vec2 SlopeDir, float Power, float Ratio)\n"
"{\n"
"  Power *= float(ImageSize.x) / 640.0;\n"
"  Ratio /= 100.0;\n"
"  vec2 vdiff;\n"
"  if (analytic)\n"
"  {\n"
"    vec2 DE = getDE();\n"
"    vdiff = vec2(1.0, -1.0) * DE / dot(DE, DE);\n"
"  }\n"
"  else\n"
"  {\n"
"    float49 N = getN();\n"
"    vdiff.x = -sub(getN(ivec2(1, 0)), N).x[0];\n"
"    vdiff.y = sub(getN(ivec2(0, -1)), N).x[0];\n"
"  }\n"
"  float diff = dot(vdiff, SlopeDir);\n"
"  diff *= Power;\n"
"  if (diff >= 0.0)\n"
"  {\n"
"    diff = atan(diff) / (pi / 2.0);\n"
"    diff = diff * Ratio;\n"
"    return vec4(vec3(0.0), diff);\n"
"  }\n"
"  else\n"
"  {\n"
"    diff = -diff;\n"
"    diff = atan(diff) / (pi / 2.0);\n"
"    diff = diff * Ratio;\n"
"    return vec4(vec3(1.0), diff);\n"
"  }\n"
"}\n"
"\n"
"float49 KF_InverseTransition(float49 iter)\n"
"{\n"
"  float49 iter_ = floor(iter);\n"
"  float offs = sub(iter, iter_).x[0];\n"
"  iter = add(iter_, 1.0 - offs);\n"
"  return iter;\n"
"}\n"
"\n"
"float49 KF_IterTransform(float49 iter0)\n"
"{\n"
"  float49 iter = iter0;\n"
"  switch (KFP_ColorMethod)\n"
"  {\n"
"    default:\n"
"    case ColorMethod_Standard: iter = iter; break;\n"
"    case ColorMethod_SquareRoot: iter = sqrt(max(0.0, iter)); break;\n"
"    case ColorMethod_CubicRoot: iter = cbrt(max(0.0, iter)); break;\n"
"    case ColorMethod_Logarithm: iter = log(max(1.0, iter)); break;\n"
"    case ColorMethod_LogLog: iter = log(add(1.0, log(add(1.0, iter)))); break;\n"
"    case ColorMethod_ATan: iter = atan(iter); break;\n"
"    case ColorMethod_FourthRoot: iter = sqrt(sqrt(max(0.0, iter))); break;\n"
"    case ColorMethod_Stretched:\n"
"    {\n"
"      float49 imin = float49_(KFP_IterationsMin[1], KFP_IterationsMin[0]);\n"
"      float49 imax = float49_(KFP_IterationsMax[1], KFP_IterationsMax[0]);\n"
"      iter = mul(1024.0, div(sub(iter, imin), sub(imax, imin))); break;\n"
"    }\n"
"    case ColorMethod_DistanceLinear:\n"
"    case ColorMethod_DEPlusStandard:\n"
"    case ColorMethod_DistanceLog:\n"
"    case ColorMethod_DistanceSqrt:\n"
"    {\n"
"      iter = float49_(1.0 / KF_DE(KFP_Differences));\n"
"      \n"
"      iter = mul(iter, float(ImageSize.x) / 640.0);\n"
"      if (KFP_ColorMethod == ColorMethod_DistanceSqrt || KFP_ColorMethod == ColorMethod_DEPlusStandard)\n"
"        iter = sqrt(max(0.0, iter));\n"
"      else if (KFP_ColorMethod == ColorMethod_DistanceLog)\n"
"        iter = log(max(1.0, add(1.0, iter)));\n"
"      if(gt(iter, 1024.0))\n"
"        iter = float49_(1024.0);\n"
"      if(KFP_ColorMethod == ColorMethod_DEPlusStandard && gt(iter, KFP_IterDiv))\n"
"        iter = iter0;\n"
"      break;\n"
"    }\n"
"  }\n"
"  iter = div(iter, KFP_IterDiv);\n"
"  iter = add(iter, KFP_ColorOffset);\n"
"  if (KFP_InverseTransition)\n"
"  {\n"
"    iter = KF_InverseTransition(iter);\n"
"  }\n"
"  return iter;\n"
"}\n"
"\n"
"vec3 KF_Colour(void)\n"
"{\n"
"  vec3 s = vec3(0.0);\n"
"  if (! KFP_ShowGlitches && getGlitch())\n"
"  {\n"
"    discard;\n"
"  }\n"
"  if (getInterior())\n"
"  {\n"
"    s = KFP_InteriorColor;\n"
"  }\n"
"  else\n"
"  {\n"
"    float49 iter = float49_(getN1(), getN0(), KFP_Flat ? 0.0 : 1.0 - getNF());\n"
"    iter = KF_IterTransform(iter);\n"
"    if (KFP_MultiWavesEnabled)\n"
"    {\n"
"      vec3 nRGB = KF_InfiniteWaves(KFP_Smooth, iter);\n"
"      if (KFP_MultiWavesBlend)\n"
"      {\n"
"        iter = add(iter, KFP_PhaseColorStrength / 100.0 * 1024.0 * getT());\n"
"        if (KFP_InverseTransition)\n"
"        {\n"
"          iter = KF_InverseTransition(iter);\n"
"        }\n"
"        vec3 nRGB2 = KF_Palette(wrap(div(iter, 1024.0)).x[0]);\n"
"        s = mix(nRGB, nRGB2, 0.5);\n"
"      }\n"
"      else\n"
"      {\n"
"        s = nRGB;\n"
"      }\n"
"    }\n"
"    else\n"
"    {\n"
"      iter = add(iter, KFP_PhaseColorStrength / 100.0 * 1024.0 * getT());\n"
"      if (KFP_InverseTransition)\n"
"      {\n"
"        iter = KF_InverseTransition(iter);\n"
"      }\n"
"      s = KF_Palette(wrap(div(iter, 1024.0)).x[0]);\n"
"    }\n"
"  }\n"
"  if (KFP_TextureEnabled)\n"
"  {\n"
"    vec2 tc = getCoord() + KF_TextureWarp(KFP_TexturePower, KFP_TextureRatio, KFP_SlopeDir);\n"
"    tc /= vec2(ImageSize.xy);\n"
"    s = mix(s, texture(KFP_Texture, tc).rgb, KFP_TextureMerge);\n"
"  }\n"
"  if (KFP_Slopes)\n"
"  {\n"
"    vec4 slope = KF_Slopes(KFP_Differences == Differences_Analytic, KFP_SlopeDir, KFP_SlopePower, KFP_SlopeRatio);\n"
"    s = mix(s, slope.rgb, slope.a);\n"
"  }\n"
"  if (getInterior() && ! KFP_TextureEnabled)\n"
"  {\n"
"    s = KFP_InteriorColor;\n"
"  }\n"
"  return s;\n"
"}\n"
"\n"
"void main(void)\n"
"{\n"
"  Internal_One = Internal_Zero + ImageSize.x / ImageSize.x;\n"
"  Internal_Colour = vec4(clamp(colour(), vec3(0.0), vec3(65504.0)), 1.0);\n"
"}\n"
"\n"
"#line 0 1\n"
;
